// 1~6
var en = new Array(
	//1
	new Array(
		new Array("1","once","從前；曾經；一旦","adv. / conj.",""),
		new Array("1","mice","鼠(複數)","n.",""),
		new Array("1","mouse","鼠(單數)","n.",""),
		new Array("1","hole","洞；孔","n.",""),
		new Array("1","farmhouse","農舍","n.",""),
		new Array("1","pleasant","令人愉快的","adj,","",""),
		new Array("1","please","使…高興；取悅","v,","",""),
		new Array("1","advice","忠告；勸告","n,","",""),
		new Array("1","advise","勸告；建議","v,","",""),
		new Array("1","quietly","安靜地","adv,","",""),
		new Array("1","slight","輕微的","adj,","",""),
		new Array("1","still","靜止的；不動的","adj,","= motionless",""),
		new Array("1","while","一段時間","n, ","",""),
		new Array("1","badly","極度；非常","adv,","",""),
		new Array("1","opening","洞口；空隙","n,","",""),
		new Array("1","immediately","馬上；立刻","adv,","= at once= right now= in seconds",""),
		new Array("1","chase","追趕","v,","= run after",""),
		new Array("1","proudly","自豪地","adv,","",""),
		new Array("1","not…any longer","不再","片語","= no longer= not anymore",""),
		new Array("1","wake up","喚醒某人","片語","",""),
		new Array("1","run away","逃走","片語","",""),
		new Array("1","be afraid of","害怕","片語","",""),
		new Array("2","scientist","科學家","n,","",""),
		new Array("2","science","科學","n,","",""),
		new Array("2","scientific","科學的","adj,","",""),
		new Array("2","wrinkle","皺紋(褶)；產生皺紋(褶)","n, / v,","",""),
		new Array("2","wrinkled","有皺紋(褶)的","adj,","",""),
		new Array("2","check","支票；檢查","n, / v,","",""),
		new Array("2","ordinary","普通的；平常的","adj,","",""),
		new Array("2","principal","(中小學的)校長","n,","",""),
		new Array("2","success","成功","n,","",""),
		new Array("2","successful","成功的","adj,","",""),
		new Array("2","succeed","成功","v,","",""),
		new Array("2","violin","小提琴","n,","",""),
		new Array("2","universe","宇宙","n,","",""),
		new Array("2","universal","普遍性的；全球的","adj,","",""),
		new Array("2","publish","發表；公佈；出版","v,","= bring out",""),
		new Array("2","theory","理論；學說","n,","",""),
		new Array("2","theoretical","理論上的","adj,","",""),
		new Array("2","travel","旅行(遊)","n, / v,","",""),
		new Array("2","quickly","快速地；迅速地","adv,","",""),
		new Array("2","quick","快速的；迅速的","adj,","= fast = rapid= swift =speedy",""),
		new Array("2","receive","收到","v,","",""),
		new Array("2","however","無論如何；然而","adv, / conj,","",""),
		new Array("2","question","問題；質問","n, / v,","",""),
		new Array("2","physics","物理學","n, ","",""),
		new Array("2","Germany","德國","n, ","",""),
		new Array("2","the Nobel Prize","諾貝爾獎","n,","",""),
		new Array("2","go for a walk","散步","片語","= take a walk",""),
		new Array("2","at first","首先；起初","片語","",""),
		new Array("2","laugh at","嘲笑","片語","",""),
		new Array("2","come to power","掌權","片語","",""),
		new Array("3","farmer","農夫","n. / v.","",""),
		new Array("3","farm","農田；耕作","n.","",""),
		new Array("3","field","牧場；田野","n.","",""),
		new Array("3","rabbit","兔子","n.","",""),
		new Array("3","away","離開","adv.","",""),
		new Array("3","fence","籬笆；柵欄","n.","",""),
		new Array("3","head","朝...前進；頭","v. / n.","",""),
		new Array("3","wood","木材","n.","woods=forest",""),
		new Array("3","wooden","木製的","adj.","",""),
		new Array("3","hunt","打獵；搜索","v.","",""),
		new Array("3","hunter","獵人","n.","",""),
		new Array("3","exhausted","筋疲力竭的","adj.","",""),
		new Array("3","exhaust","使人筋疲力竭；廢氣","v. / n.","",""),
		new Array("3","puff","喘氣；吹熄","v.","",""),
		new Array("3","silly","愚蠢的；可笑的","adj.","",""),
		new Array("3","joke","笑話","n.","",""),
		new Array("3","matter","要緊；有關係；事情","v. / n.","",""),
		new Array("3","beagle","米格魯","n.","",""),
		new Array("3","all at once","突然間","片語"," = suddenly",""),
		new Array("3","turn out to be","(結果)成為…","片語","",""),
		new Array("4","chew","咀嚼","v.","",""),
		new Array("4","gum","膠；膠狀物","n.","",""),
		new Array("4","inventor","發明家","n.","",""),
		new Array("4","invent","發明","v.","",""),
		new Array("4","invention","發明","n.","",""),
		new Array("4","liquid","液體；流質","n.","",""),
		new Array("4","rubber","橡膠","n.","",""),
		new Array("4","instead","取而代之地；反而","adv. ","",""),
		new Array("4","company","公司","n. ","",""),
		new Array("4","billion","十億","n. ","",""),
		new Array("4","stick","棒狀物；黏","n. / v.","",""),
		new Array("4","ton","噸","n.","",""),
		new Array("4","percent","百分比","n.","",""),
		new Array("4","sign","標誌；符號","n.","",""),
		new Array("4","signature","簽名","n.","",""),
		new Array("4","Sweden","瑞典","n.","",""),
		new Array("4","Mexico","墨西哥","n.","",""),
		new Array("4","take off","脫下；(飛機)起飛","片語","",""),
		new Array("4","a piece of","一片；一張","片語","",""),
		new Array("4","at one time","曾有一度；往昔","片語","",""),
		new Array("4","clean up","把...清理乾淨；整理","片語","",""),
		new Array("4","trash can","垃圾桶","片語","",""),
		new Array("5","notice","注意","v.","",""),
		new Array("5","language","語言","n.","",""),
		new Array("5","traffic","交通","n.","",""),
		new Array("5","communicate","溝通","v.","",""),
		new Array("5","communication","溝通","n.","",""),
		new Array("5","rely","依賴","v.","",""),
		new Array("5","reliable","可依賴的；可靠的","adj.","",""),
		new Array("5","entire","全部的；完全的","adj."," = whole = total",""),
		new Array("5","symbol","符號；象徵","n."," = complete",""),
		new Array("5","necessary","必需(要)的","adj.","",""),
		new Array("5","necessarily","必定地","adv.","",""),
		new Array("5","necessity","必須品","n.","",""),
		new Array("5","international","國際的","adj.","",""),
		new Array("5","common","普遍的","adj.","",""),
		new Array("5","highway","公路；大道","n."," = universal",""),
		new Array("5","cart","手推車","n.","",""),
		new Array("5","luggage","行李","n.","",""),
		new Array("5","deer","鹿(單複數同形)","n."," = baggage",""),
		new Array("5","cattle","牛(單複數同形)","n.","",""),
		new Array("5","wander","漫步；徘徊","v.","",""),
		new Array("5","unfortunately","不幸地","adv.","",""),
		new Array("5","fortunate","幸運的","adj.","",""),
		new Array("5","fortune","運氣；財富","n.","",""),
		new Array("5","situation","情形","n."," = condition",""),
		new Array("5","replace","取代","v.","",""),
		new Array("5","include","包含","v.","",""),
		new Array("5","entrance","入口","n. ","",""),
		new Array("5","exit","出口","n. ","",""),
		new Array("5","therefore","因此","adv."," = as a result",""),
		new Array("5","can’t help but + v","無法不...；一定會...","片語","",""),
		new Array("5","look for","找尋","片語","",""),
		new Array("5","as well as","和；還有","片語","",""),
		new Array("6","specific","明確的；特定的","adj.","",""),
		new Array("6","search","尋找；搜尋","n.","",""),
		new Array("6","probably","或許；大概","adv.","",""),
		new Array("6","available","可獲得的；可利用的","adj.","",""),
		new Array("6","strike","打擊；罷工；(某念頭)忽然浮現於...","v.","pt及pp為struck",""),
		new Array("6","website","網站","n.","",""),
		new Array("6","compare","比較","v.","",""),
		new Array("6","click","(按滑鼠的)卡答聲","n.","",""),
		new Array("6","variety","變化；多樣性","n.","",""),
		new Array("6","various","不同的；多種類的","adj.","",""),
		new Array("6","admit","承認；認可","v.","",""),
		new Array("6","address","地址","n.","",""),
		new Array("6","shipping","運送；載貨","n.","",""),
		new Array("6","handling","處理","n.","",""),
		new Array("6","handle","處理","v.","",""),
		new Array("6","fee","費用","n.","",""),
		new Array("6","intend","打算；企圖","v.","",""),
		new Array("6","intention","意圖","n.","",""),
		new Array("6","regular","一般的；規律的","adj.","",""),
		new Array("6","via","透過；經由","prep.","",""),
		new Array("6","online","線上的","adj.","",""),
		new Array("6","keyword","關鍵字","n.","",""),
		new Array("6","option","選擇","n.","",""),
		new Array("6","drawback","缺點(失)","n.","",""),
		new Array("6","what’s more","此外","片語","",""),
		new Array("6","get carried away","著迷；沉迷；失控","片語","",""),
		new Array("6","camera","照相機","n.","",""),
		new Array("6","convenient","方便的","adj.","",""),
		new Array("6","price","價格","n.","",""),
		new Array("7","university","大學","n.","",""),
		new Array("7","major","主修...的學生","n.","",""),
		new Array("7","quiz","小考","n.","",""),
		new Array("7","midterm","期中考","n.","",""),
		new Array("7","average","平均；平均的；一般的","n. / adj.","",""),
		new Array("7","final","最後的；期末考","adj. / n.","",""),
		new Array("7","exam","考試","n.","",""),
		new Array("7","party","派對；宴會","n.","",""),
		new Array("7","heartily","盡興地；誠摯地；熱切地","adv.","",""),
		new Array("7","hearty","衷心的；誠摯的","adj.","",""),
		new Array("7","professor","教授","n.","",""),
		new Array("7","reason","理由","n.","",""),
		new Array("7","relieved","放心的；寬心的","adj.","",""),
		new Array("7","relieve","解脫；寬慰","v.","",""),
		new Array("7","fool","愚弄；欺騙；傻瓜","v. / n.","",""),
		new Array("7","separate","分開的；分離；分居","adj. / v.","",""),
		new Array("7","alone","獨自","adv.","",""),
		new Array("7","worth","有...價值的；價值","adj. / n.","",""),
		new Array("7","ridiculous","可笑的；荒謬的","adj.","",""),
		new Array("7","ridicule","嘲笑；戲弄","n. / v.","",""),
		new Array("7","ace","表現傑出","v.","",""),
		new Array("7","thoughtfully","若有所思地","adv.","",""),
		new Array("7","brag","自誇；吹牛","v.","",""),
		new Array("7","excuse","藉口","n.","",""),
		new Array("7","instead of","取代；而不","片語","",""),
		new Array("7","make it","成功","片語","",""),
		new Array("7","as a result","因此","片語"," = therefore",""),
		new Array("7","a flat tire","輪胎漏氣","片語","",""),
		new Array("7","in time","及時","片語","",""),
		new Array("7","for a while","ㄧ會兒","片語","",""),
		new Array("8","celebrate","慶祝","n.","",""),
		new Array("8","celebration","慶祝(會)","n.","",""),
		new Array("8","hang","掛","v.","",""),
		new Array("8","temple","寺廟","n.","",""),
		new Array("8","launch","使升空；開始實行…","v.","",""),
		new Array("8","create","創造","v.","",""),
		new Array("8","creative","有創造力的","adj.","",""),
		new Array("8","peaceful","安靜的；寧靜的","adj.","",""),
		new Array("8","peace","和平","n.","",""),
		new Array("8","scene","景色","n.","",""),
		new Array("8","scenery","風景","n.","不可數名詞",""),
		new Array("8","century","世紀","n.","",""),
		new Array("8","robber","強盜；盜匪","n.","",""),
		new Array("8","rob","搶劫","v.","rob 人 of 事",""),
		new Array("8","robbery","搶劫","n.","",""),
		new Array("8","attack","攻擊","n. / v.","",""),
		new Array("8","village","村落","n.","",""),
		new Array("8","return","回去；歸還","n. / v.","",""),
		new Array("8","nowadays","現在","adv.","",""),
		new Array("8","message","消息","n.","",""),
		new Array("8","prayer","祈禱語；祝禱詞","n.","",""),
		new Array("8","pray","禱告","v.","",""),
		new Array("8","certainly","當然","adv.","",""),
		new Array("8","unforgettable","令人難忘的","adj."," = memorable",""),
		new Array("8","experience","經驗；體驗","n. / v.","",""),
		new Array("8","experienced","有經驗的","adj.","",""),
		new Array("8","northern","北方的","adj.","",""),
		new Array("8","north","北方","n.","",""),
		new Array("8","beauty","美麗；美人","n.","",""),
		new Array("8","beautiful","美麗的","adj.","",""),
		new Array("8","lantern","燈籠","n.","",""),
		new Array("8","fireworks","煙火","n.","",""),
		new Array("8","firecracker","鞭炮","n.","",""),
		new Array("8","set off","施放","片語","",""),
		new Array("8","trace(date)...back to...","追溯至...","片語","","")
	),
	//2
	new Array(
		new Array("1","laughter","笑","n.","",""),
		new Array("1","laugh","笑","v.","",""),
		new Array("1","muscle","肌肉","n.","",""),
		new Array("1","muscular","肌肉發達的","adj.","",""),
		new Array("1","breathe","呼吸","v.","",""),
		new Array("1","breath","呼吸；氣息","n.","",""),
		new Array("1","chest","胸部；有蓋的箱子","n.","",""),
		new Array("1","blood","血液","n.","",""),
		new Array("1","bloody","血的；血腥的","adj.","",""),
		new Array("1","pressure","壓力","n.","",""),
		new Array("1","press","按；壓","v.","",""),
		new Array("1","circulation","循環","n.","",""),
		new Array("1","circulate","循環；散播","v.","",""),
		new Array("1","brain","腦；智力","n.","",""),
		new Array("1","heartbeat","心跳","n.","",""),
		new Array("1","natural","自然的；天生的","adj.","",""),
		new Array("1","nature","自然；天性","n.","",""),
		new Array("1","painkiller","止痛藥","n.","",""),
		new Array("1","relaxation","放鬆","n.","",""),
		new Array("1","relax","使…放鬆","v.","",""),
		new Array("1","improve","改善","v.","",""),
		new Array("1","improvement","改善；改良","n.","",""),
		new Array("1","afterwards","之後；以後","adv.","",""),
		new Array("1","shoulder","肩膀","n.","",""),
		new Array("1","India","印度","n.","",""),
		new Array("1","go down","下降","片語","",""),
		new Array("1","the same…as…","與…相同","片語","",""),
		new Array("1","all kinds of","各式各樣的","片語"," = a variety of",""),
		new Array("1","a kind of","一種","片語","",""),
		new Array("1","be able to","能夠","片語","",""),
		new Array("2","shout","吼叫；大聲喊","n. / v.","",""),
		new Array("2","excite","使…興奮；使…刺激","v.","",""),
		new Array("2","excited","感到興奮(刺激)的","adj.","",""),
		new Array("2","exciting","令人興奮的；令人覺得刺激的","adj.","",""),
		new Array("2","college","大學；學院","n.","",""),
		new Array("2","event","場合；事件","n.","",""),
		new Array("2","male","雄性；雄性的；男人的","n. / adj.","",""),
		new Array("2","female","雌性；雌性的；女人的","n. / adj.","",""),
		new Array("2","crowd","群眾","n.","",""),
		new Array("2","organize","籌辦；組織","v.","",""),
		new Array("2","organized","有組織的","adj.","",""),
		new Array("2","organizer","籌辦者；組織者","n.","",""),
		new Array("2","yell","大聲喊叫","n. / v.","",""),
		new Array("2","athlete","運動員","n.","",""),
		new Array("2","athletic","像是運動員的；運動的","adj.","",""),
		new Array("2","separately","分開地；分別地","adv.","",""),
		new Array("2","throw","拋；丟","v.","",""),
		new Array("2","member","成員；會員","n.","",""),
		new Array("2","contest","競賽；比賽","n."," = competition",""),
		new Array("2","local","當地的；本土的","adj.","",""),
		new Array("2","state","州立的；州","adj. / n.","",""),
		new Array("2","cheerleader","啦啦隊員","n.","",""),
		new Array("2","cheerleading","啦啦隊表演","n.","",""),
		new Array("2","pyramid","金字塔","n.","",""),
		new Array("2","sportsman","運動員","n.","",""),
		new Array("2","sports car","跑車","n.","",""),
		new Array("2","in front of","在…之前","片語","",""),
		new Array("2","in the air","在空中","片語","",""),
		new Array("3","adult","成人","n."," = grownup",""),
		new Array("3","colony","殖民地","n.","",""),
		new Array("3","colonize","殖民","v.","",""),
		new Array("3","fight","對抗；打架；戰鬥","v. / n.","",""),
		new Array("3","independence","獨立","n.","",""),
		new Array("3","independent","獨立的","adj.","",""),
		new Array("3","dependent","依賴(靠)的","adj.","",""),
		new Array("3","depend","依靠","v.","",""),
		new Array("3","spelling","拼法；拼字","n.","",""),
		new Array("3","spell","拼(字)","v.","",""),
		new Array("3","pronounce","發音","v.","",""),
		new Array("3","pronunciation","發音","n.","",""),
		new Array("3","suggestion","建議","n.","",""),
		new Array("3","suggest","提議；建議","v.","",""),
		new Array("3","labor","勞動","v. / n.","",""),
		new Array("3","laborer","勞動者；勞工","n.","",""),
		new Array("3","origin","起因；起源","n."," = source",""),
		new Array("3","original","最初的；最早的","adj.","",""),
		new Array("3","originally","起初；原先","adv.","",""),
		new Array("3","Britain","英國；不列顛","n.","British =英國的",""),
		new Array("3","dictionary","字典","n.","",""),
		new Array("3","publish","出版；公佈","v.","",""),
		new Array("3","mean…to sb.","對某人具有…意思(重要性)","片語","",""),
		new Array("3","millions of","數以百萬的…","片語","",""),
		new Array("3","for example","舉例來說","片語"," = for instance",""),
		new Array("3","burst into laughter","突然大笑；放聲大笑","片語","",""),
		new Array("3","burst out laughing","突然大笑；放聲大笑","片語","",""),
		new Array("4","cocoon","繭","n.","",""),
		new Array("4","butterfly","蝴蝶","n.","",""),
		new Array("4","struggle","奮鬥；掙扎","v. / n.","",""),
		new Array("4","force","強迫；力量","v. / n.","",""),
		new Array("4","seem","似乎；好像","v. ","",""),
		new Array("4","progress","進步；進展","n.","",""),
		new Array("4","further","更進一步地","adv.","",""),
		new Array("4","scissors","剪刀","n.","",""),
		new Array("4","remaining","剩餘的","adj.","",""),
		new Array("4","remain","留下；保留；維持","v.","",""),
		new Array("4","bit","一點點；少量；小塊","n.","",""),
		new Array("4","swollen","腫脹的","adj.","",""),
		new Array("4","swell","腫脹","v.","",""),
		new Array("4","wing","翅膀","n.","",""),
		new Array("4","expect","期待","v.","",""),
		new Array("4","enlarge","增大","v.","",""),
		new Array("4","expand","擴大","v.","",""),
		new Array("4","support","支持","v. / n.","",""),
		new Array("4","contract","收縮；合約","v. / n.","",""),
		new Array("4","neither","兩者中任何一個都不是","代名詞","",""),
		new Array("4","crawl","爬行","v.","",""),
		new Array("4","develop","發展","v.","",""),
		new Array("4","exactly","精確地；確實地","adv.","",""),
		new Array("4","allow","允許","v.","",""),
		new Array("4","obstacle","障礙","n.","",""),
		new Array("4","cripple","使癱瘓；使成跛子；跛子","v. / n.","",""),
		new Array("4","shriveled","乾燥皺縮的","adj.","",""),
		new Array("4","tiny","微小的","adj.","",""),
		new Array("4","necessary","必須的；必要的","adj.","",""),
		new Array("4","as if","好像","片語","",""),
		new Array("4","cut off","切下；剪下","片語","",""),
		new Array("4","at any moment","隨時","片語","",""),
		new Array("4","in the meantime","在此期間；同時","片語","",""),
		new Array("4","go through","歷經","片語"," = experience",""),
		new Array("5","edible","可吃的；可食用的","adj.","",""),
		new Array("5","mysterious","神秘的","adj.","",""),
		new Array("5","mystery","神秘的事；神秘","n.","",""),
		new Array("5","illness","疾病；生病","n.","",""),
		new Array("5","terrible","可怕的；恐怖的","adj.","",""),
		new Array("5","continue","繼續","v.","",""),
		new Array("5","pain","疼痛；痛苦","n.","",""),
		new Array("5","painful","令人痛苦的","adj.","",""),
		new Array("5","favorite","最喜愛的；最喜愛的人事物","adj. / n.","",""),
		new Array("5","uncomfortable","不舒服的","adj.","",""),
		new Array("5","comfortable","舒服的","adj.","",""),
		new Array("5","comfort","舒適；安慰","v. / n.","",""),
		new Array("5","swallow","吞下；燕子","v. / n.","",""),
		new Array("5","centimeter","公分","n. ","",""),
		new Array("5","size","尺寸；大小","n.","",""),
		new Array("5","pill","藥丸","prep.","",""),
		new Array("5","through","通過","n.","",""),
		new Array("5","normal","正常的","adj.","",""),
		new Array("5","norm","標準；常態","n.","",""),
		new Array("5","breakthrough","突破","n.","",""),
		new Array("5","reach","到達；伸手所及的範圍","v. / n.","",""),
		new Array("5","download","下載","v.","",""),
		new Array("5","upload","上傳","v.","",""),
		new Array("5","surgery","手術","n."," = operation",""),
		new Array("5","surgical","外科手術的","n.","",""),
		new Array("5","surgeon","外科醫生","n.","",""),
		new Array("5","positive","積極的","adj.","",""),
		new Array("5","camera","照相機；攝影機","n.","",""),
		new Array("5","stomach","胃部；腹部","n.","",""),
		new Array("5","ordinary","普通的；一般的；平凡的","adj.","",""),
		new Array("5","medicine","藥","n.","",""),
		new Array("5","in pain","處於痛苦之中","片語","",""),
		new Array("5","take pictures","照相","片語","",""),
		new Array("5","go back to","返回","片語","",""),
		new Array("6","toon","卡通","n."," = cartoon",""),
		new Array("6","animated","動畫的；有生氣的","adj.","",""),
		new Array("6","animate","使…有活力","v.","",""),
		new Array("6","animation","動畫片；卡通片；活力","n.","",""),
		new Array("6","hit","撞擊；受歡迎的人或物","v. / n.","",""),
		new Array("6","monster","怪物","n.","",""),
		new Array("6","full-length","長篇的；標準長度的","adj.","",""),
		new Array("6","dwarf","矮子；侏儒","n.","",""),
		new Array("6","artist","藝術家","n.","",""),
		new Array("6","art","藝術","n.","",""),
		new Array("6","artistic","藝術的","adj.","",""),
		new Array("6","method","方法","n.","",""),
		new Array("6","adventure","奇遇；冒險","n.","",""),
		new Array("6","bug","蟲子；煩擾","n. / v.","",""),
		new Array("6","actor","演員","n.","",""),
		new Array("6","character","人物；性格；特質","n.","",""),
		new Array("6","Oscar","奧斯卡獎","n.","",""),
		new Array("6","box office","票房","n.","",""),
		new Array("6","include","包含","v.","",""),
		new Array("6","of all time","歷來；從古至今","片語","",""),
		new Array("6","for the first time","首次","片語","",""),
		new Array("6","do the voice","配音","片語","",""),
		new Array("6","all the time","一直；總是","片語"," = at all times",""),
		new Array("7","umbrella","雨傘","n.","",""),
		new Array("7","wonderful","美好的","adj.","",""),
		new Array("7","season","季節","n.","",""),
		new Array("7","arrangement","安排；排列","n.","",""),
		new Array("7","arrange","安排；佈置","v.","",""),
		new Array("7","constant","不斷的；持續的","adj.","",""),
		new Array("7","constantly","常常地；不斷地","adv.","",""),
		new Array("7","peddle","沿街叫賣","v.","",""),
		new Array("7","peddler","流動小販","n.","",""),
		new Array("7","cause","引起","v."," = lead to = result in",""),
		new Array("7","dear","親愛的","adj.","",""),
		new Array("7","thus","那樣；以此方式","adv.","",""),
		new Array("7","without","沒有","prep.","",""),
		new Array("7","none","毫無；沒有","代名詞","",""),
		new Array("7","overhear","偶然聽到","v.","",""),
		new Array("7","reassure","使安心","v.","",""),
		new Array("7","reassurance","安慰","n.","",""),
		new Array("7","eager","熱切的；渴望的","adj.","",""),
		new Array("7","plenty","很多；大量","代名詞","plenty of = lots of",""),
		new Array("7","perfect","完美的","adj.","",""),
		new Array("7","be worried about","擔憂；發愁","片語","",""),
		new Array("7","make a living","謀生；維生","片語","",""),
		new Array("7","for sure","肯定地；確實地","片語"," = certainly",""),
		new Array("7","use up","消耗；用盡","片語","",""),
		new Array("8","huge","巨大的","adj.","",""),
		new Array("8","machine","機器","n.","",""),
		new Array("8","dig","挖；掘","v.","pt及pp皆為dug",""),
		new Array("8","link","鏈環；連接","n. / v.","",""),
		new Array("8","tunnel","隧道；地道","n.","",""),
		new Array("8","channel","頻道；海峽","n.","",""),
		new Array("8","challenge","挑戰","n. / v.","",""),
		new Array("8","challenging","有挑戰性的","adj.","",""),
		new Array("8","engineer","工程師","n.","",""),
		new Array("8","engineering","工程學","n.","",""),
		new Array("8","underwater","在水底；吃水線以下的","","",""),
		new Array("8","accident","意外事故","","",""),
		new Array("8","disaster","災難","","",""),
		new Array("8","build","建造","","pt及pp皆為built",""),
		new Array("8","building","建築物","","",""),
		new Array("8","escape","逃生；逃走；避開","","",""),
		new Array("8","route","路線","n.","",""),
		new Array("8","actually","實際上","adv."," = in fact",""),
		new Array("8","railroad","鐵路","n.","",""),
		new Array("8","race","競賽","n. / v.","",""),
		new Array("8","amount","數量","v.","",""),
		new Array("8","dirt","泥巴；灰塵","n.","",""),
		new Array("8","dirty","骯髒的","adj.","",""),
		new Array("8","remove","移走；拿開；去除","v."," = get rid of",""),
		new Array("8","increase","增加","n. / v.","",""),
		new Array("8","increasing","持續增加的","adj.","",""),
		new Array("8","increasingly","持續增加地","adv."," = by degrees",""),
		new Array("8","project","計畫；投射","n. / v.","",""),
		new Array("8","kilometer","公里","n.","",""),
		new Array("8","meter","公尺","n.","",""),
		new Array("8","overpass","天橋；高架橋","n.","",""),
		new Array("8","underpass","地下道","n.","",""),
		new Array("8","platform","月台","n.","",""),
		new Array("8","terminal","航廈","n.","",""),
		new Array("8","highway","公路","n.","",""),
		new Array("8","freeway","高速公路","n. ","",""),
		new Array("8","bridge","橋","n. ","",""),
		new Array("8","side by side","並排；肩並肩","片語","","")
	),
	//3
	new Array(
		new Array("1","plant","植物；種植","n. / v.","",""),
		new Array("1","sunlight","陽光","n.","",""),
		new Array("1","insect","昆蟲","n.","",""),
		new Array("1","flytrap","食蟲植物","n.","",""),
		new Array("1","wetland","溼地","n.","",""),
		new Array("1","stalk","莖；花梗；葉柄","n.","",""),
		new Array("1","top","頂端；最前面的","n. / adj.","",""),
		new Array("1","leaf","葉子","n.","複數為leaves",""),
		new Array("1","sharp","尖銳的","adj."," = keen",""),
		new Array("1","spine","植物的針刺；動物的脊椎","n.","",""),
		new Array("1","trap","陷阱；(設陷阱)捕捉","n. / v.","",""),
		new Array("1","pour","傾倒；灌注","v.","",""),
		new Array("1","poison","毒藥；毒殺","n. / v.","",""),
		new Array("1","poisonous","有毒的","adj."," = toxic = venomous",""),
		new Array("1","frog","青蛙","n.","",""),
		new Array("1","stem","(花草的)莖或梗","n.","",""),
		new Array("1","carnivorous","肉食性的","adj."," = meat-eating",""),
		new Array("1","touch","接觸；碰觸","v.","",""),
		new Array("1","electric flytrap","捕蚊燈","n.","",""),
		new Array("1","catch one’s attention","吸引某人注意","片語","",""),
		new Array("1","live on","依賴…維生","片語","",""),
		new Array("1","less than","少於…","片語","",""),
		new Array("1","be ready for","準備好…","片語","",""),
		new Array("2","decide","決定","v.","",""),
		new Array("2","makeup","化妝品","n.","",""),
		new Array("2","cosmetics","化妝品","n.","",""),
		new Array("2","ash","灰燼；煙灰","n.","",""),
		new Array("2","shine","閃耀；發亮","v.","",""),
		new Array("2","shiny","發亮的","adj.","",""),
		new Array("2","marry","嫁或娶某人","v.","",""),
		new Array("2","marriage","結婚；婚姻","n.","",""),
		new Array("2","rent","租金；租用；出租","n. / v.","",""),
		new Array("2","smell","味道；發臭","n. / v.","",""),
		new Array("2","roof","屋頂","n.","",""),
		new Array("2","leak","漏洞；裂縫；漏水；漏氣","n. / v.","",""),
		new Array("2","damp","潮濕的","adj."," = moist",""),
		new Array("2","perfume","香水","n.","",""),
		new Array("2","ingredient","成分；材料","n.","",""),
		new Array("2","honey","蜂蜜","n.","",""),
		new Array("2","cucumber","黃瓜","n.","",""),
		new Array("2","strawberry","草莓","n.","",""),
		new Array("2","product","產品","n.","",""),
		new Array("2","produce","製造","v.","",""),
		new Array("2","United Nations","聯合國","n.","",""),
		new Array("2","New York","紐約","n.","",""),
		new Array("2","shampoo","洗髮精；洗髮","n. / v.","",""),
		new Array("2","use…as…","用…當作…","片語","",""),
		new Array("2","later on","後來；以後","片語","",""),
		new Array("2","fill…with…","充滿…；裝滿…","片語","",""),
		new Array("2","of course","當然","片語","",""),
		new Array("2","day and night","日以繼夜地","片語","",""),
		new Array("3","increase","增加","n. / v.","",""),
		new Array("3","improve","改善","v.","",""),
		new Array("3","symbol","象徵","n. ","",""),
		new Array("3","graduation","畢業","n.","",""),
		new Array("3","uniform","制服","n. ","",""),
		new Array("3","soldier","軍人；士兵","n.","",""),
		new Array("3","feeling","感覺","n. ","",""),
		new Array("3","spirit","精神","n.","",""),
		new Array("3","spiritual","精神的","adj.","",""),
		new Array("3","fellow","同類的","adj.","",""),
		new Array("3","identify","辨識；認同","v.","",""),
		new Array("3","identity","身分","n.","",""),
		new Array("3","identification","身分證明","n.","",""),
		new Array("3","trust","信任","v. / n.","",""),
		new Array("3","argue","爭論；主張","v.","",""),
		new Array("3","argument","論點；爭論","n.","",""),
		new Array("3","individual","個別的；個人","adj. / n.","",""),
		new Array("3","reduce","減少","v. ","",""),
		new Array("3","reduction","減少；降低","n.","",""),
		new Array("3","freedom","自由","n.","",""),
		new Array("3","supporter","支持者","n.","",""),
		new Array("3","compete","競爭","v.","",""),
		new Array("3","competitor","競爭者","n.","",""),
		new Array("3","competition","競賽","n.","",""),
		new Array("3","competitive","競爭的","adj.","",""),
		new Array("3","afford","負擔得起；有能力去做","v.","",""),
		new Array("3","affordable","負擔得起的","adj.","",""),
		new Array("3","latest","最近的；最新的","adj.","",""),
		new Array("3","fashion","流行；時尚","n.","",""),
		new Array("3","fashionable","流行的","adj.","",""),
		new Array("3","encourage","鼓勵","v.","",""),
		new Array("3","encouragement","鼓勵","n.","",""),
		new Array("3","behavior","行為","n.","",""),
		new Array("3","behave","舉止；表現","v.","",""),
		new Array("3","report","報告；舉發；告發","n. / v.","",""),
		new Array("3","pride","榮譽感；自尊；驕傲","n.","take pride in",""),
		new Array("3","proud","引以為榮的；驕傲的","adj.","be proud of",""),
		new Array("3","honor","光榮；敬重","n. / v.","",""),
		new Array("3","honorable","高貴的；可敬重的","adj.","",""),
		new Array("3","excellent","優秀的","adj.","",""),
		new Array("3","excellence","優秀","n.","",""),
		new Array("3","whatever","不管如何","代名詞","",""),
		new Array("3","opinion","意見；看法；見解","n.","",""),
		new Array("3","teammate","隊友","n.","",""),
		new Array("3","the public","大眾","片語","",""),
		new Array("3","in public","在眾人面前；在公共場合","片語","",""),
		new Array("3","in addition","除此之外，還有…","片語","",""),
		new Array("3","in particular","特別地；尤其","片語","",""),
		new Array("3","stop…from…","阻止…不要…","片語","",""),
		new Array("3","save…the trouble of…","省去…麻煩…","片語","",""),
		new Array("3","feel left out","被冷落；被遺忘；被忽略","片語","",""),
		new Array("4","active","活躍的；主動的","adj.","",""),
		new Array("4","hardly","幾乎不","adv.","",""),
		new Array("4","poem","詩","n.","",""),
		new Array("4","lifetime","一生；終生","n.","",""),
		new Array("4","poet","詩人","n.","",""),
		new Array("4","consider","認為；考慮","v."," = regard",""),
		new Array("4","consideration","考慮","n.","",""),
		new Array("4","rather","頗為；有些","adv.","",""),
		new Array("4","unusual","不尋常的","adj.","",""),
		new Array("4","death","死亡","n.","",""),
		new Array("4","dead","死的","adj.","",""),
		new Array("4","deep","深的；深奧的","adj.","",""),
		new Array("4","meaning","含義；意思","n.","",""),
		new Array("4","meaningful","有意義的","adj.","",""),
		new Array("4","meaningless","無意義的","adj.","",""),
		new Array("4","ease","減輕；舒適","v. / n.","",""),
		new Array("4","ache","疼痛","v. / n.","",""),
		new Array("4","faint","昏厥","v. ","",""),
		new Array("4","nobody","無名小卒","n.","",""),
		new Array("4","advertise","做廣告","v. ","",""),
		new Array("4","advertisement","廣告","n.","",""),
		new Array("4","dreary","無聊的；乏味的","adj.","",""),
		new Array("4","somebody","大人物","n. ","",""),
		new Array("4","admire","欽佩；讚美","v.","",""),
		new Array("4","admiration","欽佩；讚美","n.","",""),
		new Array("4","nest","鳥巢","n. ","",""),
		new Array("4","in fact","事實上","片語"," = as a matter of fact",""),
		new Array("4","figure out","解決；理解","片語"," = work out",""),
		new Array("4","in vain","枉然；徒然；無效地","片語","",""),
		new Array("4","a pair","一對","片語","",""),
		new Array("5","incident","事件","n.","",""),
		new Array("5","midnight","午夜","n.","",""),
		new Array("5","row","排；划(船)","n. / v.","",""),
		new Array("5","attendance","出席；出席人數","adj.","",""),
		new Array("5","attend","出席","v.","",""),
		new Array("5","explanation","解釋","n.","",""),
		new Array("5","explain","解釋","v.","",""),
		new Array("5","quit","停止；終止","v.","",""),
		new Array("5","truth","事實；真相","n.","",""),
		new Array("5","practically","事實上","adv.","",""),
		new Array("5","impossible","不可能的","adj.","",""),
		new Array("5","whole","全部的；完全的","adj."," = entire = complete",""),
		new Array("5","realize","了解；實現","v.","",""),
		new Array("5","apology","道歉；賠罪","n.","",""),
		new Array("5","apologize","道歉；賠罪","v.","",""),
		new Array("5","apologetic","表示歉意的；賠罪的","adj.","",""),
		new Array("5","discuss","討論；商議","v.","",""),
		new Array("5","discussion","討論；商談","n.","",""),
		new Array("5","clearly","清楚地","adv."," = obviously",""),
		new Array("5","result","結果；產生；導致","n. / v.","",""),
		new Array("5","whenever","無論何時","adv.","",""),
		new Array("5","perplexed","困惑的","adj."," = confused",""),
		new Array("5","idiom","成語","n.","",""),
		new Array("5","immediately","立刻；馬上","adv."," = at once",""),
		new Array("5","stay up","熬夜","片語"," = sit up",""),
		new Array("5","in (such) a hurry","匆忙","片語","",""),
		new Array("5","on time","準時","片語","",""),
		new Array("5","pull one’s leg","欺騙某人；愚弄某人","片語","",""),
		new Array("5","make (any) sense","有(任何)意義","片語","",""),
		new Array("5","make up ","編造；彌補；補考；化妝","片語","",""),
		new Array("5","come in handy","派上用場","片語","",""),
		new Array("5","sooner or later","遲早","片語","",""),
		new Array("5","have a sweet tooth","喜好甜食","片語","",""),
		new Array("6","festival","節慶","n.","",""),
		new Array("6","celebrate","慶祝","v.","",""),
		new Array("6","church","教堂","n.","",""),
		new Array("6","carnival","嘉年華會；狂歡節","n.","",""),
		new Array("6","last","持續；上一次；最後的","v. / adj.","",""),
		new Array("6","stone","石頭","n.","",""),
		new Array("6","dogsled","狗拉的雪橇","n.","",""),
		new Array("6","narrow","狹窄的","adj.","",""),
		new Array("6","canoe","獨木舟","n.","",""),
		new Array("6","choose","選擇","v.","pt為chose pp為chosen",""),
		new Array("6","choice","選擇","n.","",""),
		new Array("6","skiing","滑雪","n.","",""),
		new Array("6","skating","溜冰","n.","",""),
		new Array("6","completely","完全地；整個地","adv.","",""),
		new Array("6","complete","完成；全部的","v. / adj.","",""),
		new Array("6","thick","厚的","adj. ","",""),
		new Array("6","couple","數個；幾個；夫婦；一對","n.","",""),
		new Array("6","soft","軟的；不含酒精的","adj.","",""),
		new Array("6","deerskin","鹿皮","n.","",""),
		new Array("6","guest","賓客；客人","n.","",""),
		new Array("6","Quebec","魁北克","n.","",""),
		new Array("6","Canada","加拿大","n.","",""),
		new Array("6","be made of","由…製成","片語","",""),
		new Array("7","twice","兩次","adv.","",""),
		new Array("7","pool","水池","n.","",""),
		new Array("7","cigarette","香菸","n.","",""),
		new Array("7","alcoholic","酗酒者；酒精的","n. / adj.","",""),
		new Array("7","alcohol","酒；酒精","n.","",""),
		new Array("7","avoid","避免","v.","",""),
		new Array("7","fatty","多脂肪的","adj.","",""),
		new Array("7","fat","脂肪；肥胖的","n. / adj.","",""),
		new Array("7","weigh","稱重","v.","",""),
		new Array("7","weight","體重","n.","",""),
		new Array("7","daily","每日的","adj.","",""),
		new Array("7","rocking","搖晃的","adj.","",""),
		new Array("7","shake","搖動","v.","",""),
		new Array("7","shaky","發抖的","adj.","",""),
		new Array("7","teeth","牙齒","n.","單數為tooth",""),
		new Array("7","reply","回答","n. / v.","",""),
		new Array("7","secret","秘密；秘訣","n. ","",""),
		new Array("7","anywhere","任何地方","adv.","",""),
		new Array("7","wonder","想知道；奇景","v. / n.","",""),
		new Array("7","wonderful","美好的","adj.","",""),
		new Array("7","porch","(有頂之)門廊；陽台","n.","",""),
		new Array("7","pack","小包；小捆","n.","",""),
		new Array("7","whisky","威士忌酒","n.","",""),
		new Array("7","infant","嬰兒","n.","",""),
		new Array("7","adult","成年人","n."," = grownup",""),
		new Array("7","at one’s age","在某人那個年紀","片語","",""),
		new Array("7","as…as…","與…一樣","片語","",""),
		new Array("8","name","命名","v.","be named after",""),
		new Array("8","automobile","汽車","n.","",""),
		new Array("8","astounded","吃驚的","adj.","",""),
		new Array("8","astound","令…吃驚","v."," = surprise",""),
		new Array("8","hesitate","遲疑；說話支支吾吾","v.","",""),
		new Array("8","heel","腳後跟","n.","",""),
		new Array("8","astonishment","震驚；吃驚","n.","",""),
		new Array("8","astonish","使…震驚","v.","",""),
		new Array("8","astonished","令人驚愕的","adj.","",""),
		new Array("8","add","增加","v.","",""),
		new Array("8","neighbor","鄰居","n.","",""),
		new Array("8","neighborhood","鄰近地區","n.","",""),
		new Array("8","step","階梯；腳步；步伐","n.","",""),
		new Array("8","squeeze","擠進；壓擠","v.","",""),
		new Array("8","against","倚靠","prep.","",""),
		new Array("8","upstairs","在樓上；往樓上","adv.","",""),
		new Array("8","lift","舉起；抬起","v."," = elevate",""),
		new Array("8","memorable","難忘的","adj."," = unforgettable",""),
		new Array("8","memory","記憶","n.","",""),
		new Array("8","memorize","記住","v.","",""),
		new Array("8","blessed","喜悅的；(受上帝)祝福的","adj.","",""),
		new Array("8","crippled","跛腳的","adj.","",""),
		new Array("8","bottom","底部；底層的","n. / adj.","",""),
		new Array("8","hamburger","漢堡","n.","",""),
		new Array("8","chocolate","巧克力","n.","",""),
		new Array("8","vegetable","蔬菜","n.","",""),
		new Array("8","in a (little) while","不久","片語","",""),
		new Array("8","sort of","稍微；有點","片語","",""),
		new Array("8","for oneself","親自","片語","",""),
		new Array("8","head over heels","四腳朝天","片語","",""),
		new Array("8","take a ride","兜風","片語","",""),
		new Array("8","take a walk","散步","片語"," = go for a walk","")
	),
	//4
	new Array(
		new Array("1","valentine","送給情人的卡片或禮物；情人","n. ","",""),
		new Array("1","remind","提醒；使想起","v.","remind 人 of 事",""),
		new Array("1","trace","蹤跡；追蹤","n. / v.","",""),
		new Array("1","vase","花瓶","n. ","",""),
		new Array("1","exchange","交換","n. / v.","",""),
		new Array("1","ideal","理想的；理想","adj. / n.","",""),
		new Array("1","candlelit","燭光照明的","adj.","",""),
		new Array("1","candlelight","燭光","n.","",""),
		new Array("1","romantic","浪漫的","adj.","",""),
		new Array("1","romance","愛情故事；戀情","n.","",""),
		new Array("1","fancy","花俏的；昂貴的","adj.","",""),
		new Array("1","lace","雷絲織品","n.","",""),
		new Array("1","ribbon","緞帶","n.","",""),
		new Array("1","decoration","裝飾；裝飾品","n.","",""),
		new Array("1","decorate","裝飾","v.","",""),
		new Array("1","scrap","小片；碎屑","n.","",""),
		new Array("1","handwriting","筆跡；字體","n.","",""),
		new Array("1","sip","啜飲","v.","",""),
		new Array("1","wine","酒","n.","",""),
		new Array("1","newspaper","報紙","n.","",""),
		new Array("1","nickname","綽號；取綽號","n. / v.","",""),
		new Array("1","initial","起首第一個字母","n.","",""),
		new Array("1","section","(報紙的)欄；部分","n.","",""),
		new Array("1","rhyme","韻腳；押韻","n. / v.","",""),
		new Array("1","Valentine’s Day","西洋情人節","n.","",""),
		new Array("1","Roman","羅馬的；羅馬人","adj. / n.","",""),
		new Array("1","sweetheart","甜心","n.","",""),
		new Array("1","classified-ad","分類廣告","n.","",""),
		new Array("1","popular","受歡迎的","adj.","",""),
		new Array("1","famous","有名的","adj.","",""),
		new Array("1","message","訊息","n.","",""),
		new Array("1","restaurant","餐廳","n.","",""),
		new Array("1","A fall in love B","A與B墜入愛河","片語","",""),
		new Array("1","top sth. off","為…畫上完美的句點","片語","",""),
		new Array("2","southern","南方的","adj.","",""),
		new Array("2","south","南方","n.","",""),
		new Array("2","southerner","南方人","n.","",""),
		new Array("2","continent","洲；大陸","n.","",""),
		new Array("2","tip","頂點；小費；給小費","n. / v.","",""),
		new Array("2","rise","上升；漸高","v. / n.","",""),
		new Array("2","coast","海岸","n.","",""),
		new Array("2","coastal","海岸的","adj.","",""),
		new Array("2","plain","平原；樸素的；清楚的","n. / adj.","",""),
		new Array("2","elevation","海拔；高度；提升","n.","",""),
		new Array("2","elevate","舉起；提起","v."," = lift",""),
		new Array("2","elevator","電梯；升降機","n.","",""),
		new Array("2","escalator","電動手扶梯","n.","",""),
		new Array("2","desert","沙漠；遺棄；拋棄","n. / v.","",""),
		new Array("2","empty","空的；騰空；掏空","adj.","",""),
		new Array("2","emptiness","空洞；空虛","n. / v.","",""),
		new Array("2","glacier","冰河","n.","",""),
		new Array("2","everywhere","到處；四處","adv.","",""),
		new Array("2","area","地區","n.","",""),
		new Array("2","penguin","企鵝","n.","",""),
		new Array("2","experiment","實驗；試驗","n. / v.","",""),
		new Array("2","emergency","危急；緊急","n.","",""),
		new Array("2","emergent","緊急的","adj."," = critical",""),
		new Array("2","cancer","癌症；腫瘤","n.","",""),
		new Array("2","cancel","取消","v."," = call off",""),
		new Array("2","medical","醫療的；醫學的","adj.","",""),
		new Array("2","Australia","澳洲","n.","",""),
		new Array("2","belong to ","屬於","片語","",""),
		new Array("2","take care of","照顧","片語"," = look after",""),
		new Array("2","have no choice but to + V","沒有其他選擇，只好…","片語","",""),
		new Array("3","mysterious","神秘的","adj.","",""),
		new Array("3","mystery","神秘的事；神秘","n.","",""),
		new Array("3","stomach","胃部","n.","",""),
		new Array("3","diary","日記","n.","",""),
		new Array("3","theory","原理；理論","n.","",""),
		new Array("3","landscape","景色；風景","n.","",""),
		new Array("3","straight","筆直的(地)；直接的(地)","adj. / adv.","",""),
		new Array("3","portrait","畫作；畫像","n.","",""),
		new Array("3","setting","(故事、畫作的)時空背景","n.","",""),
		new Array("3","pose","擺姿勢；引起(問題)","v.","",""),
		new Array("3","model","模特兒","n.","",""),
		new Array("3","definite","明確的","adj. "," = certain = absolute",""),
		new Array("3","definitely","一定地；無疑地","adv.","",""),
		new Array("3","proof","證據","n.","",""),
		new Array("3","prove","證明","v.","",""),
		new Array("3","photograph","相片","n.","",""),
		new Array("3","photography","攝影","n.","",""),
		new Array("3","photographer","攝影師","n.","",""),
		new Array("3","corner","角落","n.","",""),
		new Array("3","skin","人的皮膚；果皮","n.","",""),
		new Array("3","skinny","極瘦的","adj.","",""),
		new Array("3","beat","心跳；擊敗；打","v.","",""),
		new Array("3","sadness","悲傷；難過","n."," = grief = sorrow",""),
		new Array("3","mischief","惡作劇；淘氣的行為","n.","",""),
		new Array("3","mischievous","頑皮的","adj.","",""),
		new Array("3","forever","永遠地","adv."," = for good",""),
		new Array("3","resemblance","相似；相像","n.","",""),
		new Array("3","realistically","寫實地；逼真地","adv.","",""),
		new Array("3","blurred","模糊的；朦朧的","adj."," = unclear",""),
		new Array("3","be dressed as","裝扮成…","片語","",""),
		new Array("3","look away","把眼光移開","片語","",""),
		new Array("3","keep good time","(鐘、錶)時間很準","片語","",""),
		new Array("4","rocket","火箭；迅速上升","n. / v.","",""),
		new Array("4","groceries","雜貨","n.","",""),
		new Array("4","grocery","雜貨店","n.","",""),
		new Array("4","housekeeper","管家","n.","",""),
		new Array("4","robot","機器人","n.","",""),
		new Array("4","viewer","觀眾","n.","",""),
		new Array("4","view","景色；看法；認(視)為","n. / v.","view A as B 把A視為B",""),
		new Array("4","predict","預測","v."," = forecast",""),
		new Array("4","prediction","預測；預言","n.","",""),
		new Array("4","manufacture","生產；製造","v.","",""),
		new Array("4","manufacturer","製造商","n.","",""),
		new Array("4","assemble","裝配；集合；組合","v."," = put together",""),
		new Array("4","assembly","裝配；集合","n.","",""),
		new Array("4","electronic","(有關)電子的","adj.","",""),
		new Array("4","electric","電的；帶電的","adj.","",""),
		new Array("4","electricity","電；電流","n.","",""),
		new Array("4","device","器具；裝置","n.","",""),
		new Array("4","devise","設計","v.","",""),
		new Array("4","explore","探勘；探索","v.","",""),
		new Array("4","planet","行星","n.","",""),
		new Array("4","investigate","調查；探究","v.","#NAME?",""),
		new Array("4","investigation","調查","n.","",""),
		new Array("4","trade","交易；買賣","n. / v.","",""),
		new Array("4","trader","商人；貿易業者","n.","",""),
		new Array("4","entertain","娛樂","v.","",""),
		new Array("4","entertainment","娛樂","n."," = recreation",""),
		new Array("4","bark","狗吠聲；吠","n. / v.","",""),
		new Array("4","mess","雜亂；不整齊","n.","",""),
		new Array("4","messy","雜亂的；不整齊的","adj.","",""),
		new Array("4","housework","家事","n.","",""),
		new Array("4","main","主要的","adj."," = chief = principal",""),
		new Array("4","power","電力；權力；供應電力","n. / v.","",""),
		new Array("4","battery","電池","n.","",""),
		new Array("4","purpose","目的；用途；意圖","n."," = aim = intention",""),
		new Array("4","design","圖樣；設計","n. / v.","",""),
		new Array("4","designer","設計師","n.","",""),
		new Array("4","chore","家庭雜務","n.","",""),
		new Array("4","dusting","打掃；拂拭","n.","",""),
		new Array("4","dust","灰塵；除去灰塵","n. / v.","",""),
		new Array("4","vacuum","吸塵器；用吸塵器打掃","n. / v.","",""),
		new Array("4","interior","內部的；內部","adj. / n.","",""),
		new Array("4","Egypt","埃及","n.","",""),
		new Array("4","wreckage","殘骸","n.","",""),
		new Array("4","bartender","調酒師；酒吧的侍者","n.","",""),
		new Array("4","recharge","充電","v. ","",""),
		new Array("4","gourmet","美食的","adj.","",""),
		new Array("4","diaper","尿布","n.","",""),
		new Array("4","ordinary","普通的；一般的","adj."," = common",""),
		new Array("4","various","各式各樣的","adj.","",""),
		new Array("4","dangerous","危險的","adj.","",""),
		new Array("4","pyramid","金字塔","n.","",""),
		new Array("4","search","尋找；搜尋","n. / v.","",""),
		new Array("4","available","可利用的","adj.","",""),
		new Array("4","engineer","工程師","n.","",""),
		new Array("4","at the time","當時","片語","",""),
		new Array("4","in use","正使用中","片語","",""),
		new Array("4","in the near future","不久的將來","片語","",""),
		new Array("5","humankind","(全體)人類","n."," = human being",""),
		new Array("5","diligence","勤勞","n.","",""),
		new Array("5","diligent","勤勞的","adj."," = hard-working",""),
		new Array("5","despite","儘管","prep.","",""),
		new Array("5","weak","虛弱的","adj.","",""),
		new Array("5","weaken","使變弱","v.","",""),
		new Array("5","weakness","虛弱；弱點；缺點","n.","",""),
		new Array("5","heaven","天堂","n.","",""),
		new Array("5","steal","偷","v.","pt.為stole pp.為stolen",""),
		new Array("5","creature","生物","n.","",""),
		new Array("5","discover","發現；找出","v.","",""),
		new Array("5","discovery","發現","n.","",""),
		new Array("5","fear","害怕","n. / v.","",""),
		new Array("5","punish","處罰","v.","",""),
		new Array("5","punishment","懲罰","n.","",""),
		new Array("5","grace","優雅；典雅","n.","",""),
		new Array("5","jewelry","珠寶","n.","集合名詞，沒有複數形式",""),
		new Array("5","jewel","珠寶","n.","",""),
		new Array("5","present","禮物；出席的；目前的；提出","n. / adj. / v.","",""),
		new Array("5","indeed","的確","adv.","",""),
		new Array("5","curiosity","好奇心","n.","",""),
		new Array("5","curious","好奇的","adj.","",""),
		new Array("5","specifically","明確地；特定地","adv.","",""),
		new Array("5","obey","服從；遵守","v.","",""),
		new Array("5","control","控制","n. / v.","",""),
		new Array("5","ugly","醜陋的；難看的","adj.","",""),
		new Array("5","disease","疾病","n."," = illness",""),
		new Array("5","wicked","邪惡的","adj.","",""),
		new Array("5","emotion","情感；情緒","n.","",""),
		new Array("5","jealous","嫉妒","adj.","",""),
		new Array("5","jealousy","嫉妒的","n.","",""),
		new Array("5","loneliness","孤獨；寂寞","n.","",""),
		new Array("5","sorrow","悲傷","n."," = grief = sadness",""),
		new Array("5","lid","蓋子","n.","",""),
		new Array("5","evil","罪惡；邪惡；邪惡的","adj. / n.","",""),
		new Array("5","item","物品；項目","n.","",""),
		new Array("5","contain","包含","v.","",""),
		new Array("5","container","容器","n.","",""),
		new Array("5","suffering","苦難；痛苦","n.","",""),
		new Array("5","suffer","受苦；患病；經歷；遭受","v."," = go through",""),
		new Array("5","impulse","衝動；一時的念頭","n.","",""),
		new Array("5","stubborn","固執的","adj."," = headstrong",""),
		new Array("5","selfish","自私的","adj.","",""),
		new Array("5","arrogant","傲慢的；自大的","adj."," = proud",""),
		new Array("5","set about","著手；開始做…","片語","",""),
		new Array("5","take a look at","看一看","片語","",""),
		new Array("5","at the bottom of","在…的底部","片語","",""),
		new Array("5","to this day","直到今日；直到現在","片語","",""),
		new Array("6","verbal","用語言表達的；口頭的","adj.","",""),
		new Array("6","verbally","口頭地","adv.","",""),
		new Array("6","nonverbal","非語言地；不涉及語言地","adj.","",""),
		new Array("6","universal","一般的；普遍的；人類全體的","adj.","",""),
		new Array("6","relaxed","輕鬆的","adj.","",""),
		new Array("6","second","秒；次要的；第二的","n. / adj.","",""),
		new Array("6","stare","凝視；瞪眼看","v.","",""),
		new Array("6","impolite","沒禮貌的","adj.","",""),
		new Array("6","greet","打招呼","v.","",""),
		new Array("6","greeting","迎接；招呼","n.","",""),
		new Array("6","handshake","握手","n.","",""),
		new Array("6","custom","風俗；習慣","n.","",""),
		new Array("6","customer","顧客","n.","",""),
		new Array("6","tight","緊的","adj.","",""),
		new Array("6","gentle","輕輕的","adj.","",""),
		new Array("6","gently","輕柔地","adv.","",""),
		new Array("6","signal","信號；手勢；打信號","n. / v.","",""),
		new Array("6","misunderstanding","誤解","n.","",""),
		new Array("6","understanding","了解","n. ","",""),
		new Array("6","thumb","大拇指","n.","",""),
		new Array("6","forefinger","食指","n.","",""),
		new Array("6","opposite","相反的事物；相反的；在對面","n. / adj. / prep.","",""),
		new Array("6","insult","侮辱","n. / v.","",""),
		new Array("6","hug","擁抱","n. / v."," = embrace",""),
		new Array("6","disagree","不同意","v.","",""),
		new Array("6","disagreement","意見相左","n.","",""),
		new Array("6","tap","輕拍；輕敲","n. / v.","pt及pp皆為tapped",""),
		new Array("6","patient","病人；有耐性的","n. / adj.","",""),
		new Array("6","impatient","缺乏耐性的","adj.","",""),
		new Array("6","patience","不耐煩","n.","",""),
		new Array("6","tense","緊張的；緊繃","adj. / v.","",""),
		new Array("6","nerve","神經","n.","",""),
		new Array("6","nervous","緊張的","adj.","",""),
		new Array("6","communicate","溝通","v.","",""),
		new Array("6","culture","文化","n. ","",""),
		new Array("6","circle","圓圈；畫圓圈","n. / v.","",""),
		new Array("6","Spanish","西班牙語","n. ","",""),
		new Array("6","Japanese","日文","n.","",""),
		new Array("6","Arabic","阿拉伯語","n.","",""),
		new Array("6","turn away","轉身離開","片語","",""),
		new Array("6","from side to side","左右地","片語","",""),
		new Array("6","lose face","丟臉","片語","",""),
		new Array("7","appear","出現","v."," = show up",""),
		new Array("7","friendly","友善的","adj.","",""),
		new Array("7","temperature","溫度","n.","",""),
		new Array("7","cheerful","快樂的；令人愉快的","adj.","",""),
		new Array("7","affect","影響","v."," = influence",""),
		new Array("7","affective","情緒的；感情的","adj.","",""),
		new Array("7","mood","心情","n.","",""),
		new Array("7","stormy","狂暴的","adj.","",""),
		new Array("7","psychologist","心理學家","n. ","",""),
		new Array("7","psychology","心理學","n. ","",""),
		new Array("7","depress","使沮喪；使消沉","v."," = discourage",""),
		new Array("7","depressed","沮喪的；憂鬱的","adj.","",""),
		new Array("7","depression","沮喪心情；意氣消沉","n.","",""),
		new Array("7","indoors","室內地","adv.","",""),
		new Array("7","sensitive","敏感的","adj.","",""),
		new Array("7","routine","例行公事；慣例","n. ","",""),
		new Array("7","condition","情況；狀態","n."," = situation",""),
		new Array("7","lack","欠缺；缺少","n. / v.","",""),
		new Array("7","particularly","尤其；特別地","adv."," = especially",""),
		new Array("7","region","地區；地帶","n."," = area",""),
		new Array("7","optimistic","樂觀的","adj.","",""),
		new Array("7","optimist","樂觀者","n.","",""),
		new Array("7","pessimistic","悲觀的","adj.","",""),
		new Array("7","humid","潮濕的","adj."," = damp = moist",""),
		new Array("7","humidity","溼度；溼氣","n.","",""),
		new Array("7","aggressive","有進取精神的；有攻擊性的","adj.","",""),
		new Array("7","prefer","較喜歡","v.","",""),
		new Array("7","moderate","適度的；中等的","adj.","",""),
		new Array("7","breeze","微風；和風","n.","",""),
		new Array("7","generally","通常地；一般地","adv.","",""),
		new Array("7","degree","度數","n.","",""),
		new Array("7","period","時期","n."," = era = age = times",""),
		new Array("7","sunshine","陽光","n.","",""),
		new Array("7","appeal","吸引力；吸引","n. / v."," = attract (v.)",""),
		new Array("7","effect","影響；效力","n.","",""),
		new Array("7","effective","有效的","adj.","",""),
		new Array("7","express","表達","v.","",""),
		new Array("7","expression","措辭；表達","n.","",""),
		new Array("7","relationship","關係","n.","",""),
		new Array("7","weather-related","","與天氣相關的","adj.","",""),
		new Array("7","hot-blooded","熱血的","adj.","",""),
		new Array("7","disposition","性格；性情","n.","",""),
		new Array("7","bring on","引起；導致","片語"," = cause = lead to = give rise to   = result in",""),
		new Array("7","carry out","實行","片語","",""),
		new Array("7","due to + N","由於；因為","片語"," = because of + N    = thanks to + N",""),
		new Array("7","in contrast","相反地；相較地","片語"," = on the contrary",""),
		new Array("7","tend to + V","有…的傾向","片語","",""),
		new Array("7","look forward to + N","盼望；期待","片語","",""),
		new Array("7","from time to time","有時候；偶爾","片語","#NAME?",""),
		new Array("7","give sb. the cold shoulder","對…冷淡","片語","",""),
		new Array("7","in a row","連續地","片語"," = continually",""),
		new Array("8","thanks to + N","還好有…；由於…；多虧有…","片語","",""),
		new Array("8","owing to + N","因為","片語","",""),
		new Array("8","when it comes to + N","說到…","片語","",""),
		new Array("8","lead to + N","導致","片語","",""),
		new Array("8","in addition to + N","除了…之外，還有…","片語","",""),
		new Array("8","pay attention to + N","注意","片語","",""),
		new Array("8","be used to + N","習慣於…","片語","",""),
		new Array("8","object to + N","反對","片語","",""),
		new Array("8","be devoted to + N","致力於…","片語","",""),
		new Array("8","cling to + N","依附；堅持","片語","",""),
		new Array("8","belong to + N","屬於","片語","",""),
		new Array("8","be unaware of","不知道","片語","",""),
		new Array("8","workplace","職場","n.","",""),
		new Array("8","speed","速度；加速","n. / v.","",""),
		new Array("8","postal","郵政的","adj.","",""),
		new Array("8","postage","郵資","n.","",""),
		new Array("8","system","系統","n.","",""),
		new Array("8","systematic","有系統的","adj.","",""),
		new Array("8","snail","蝸牛","n.","",""),
		new Array("8","survey","調查","n. / v.","",""),
		new Array("8","conduct","行為；進行；展開","n. / v.","",""),
		new Array("8","provide","提供","v.","",""),
		new Array("8","provider","供應者；業者","n.","",""),
		new Array("8","basic","基本的","adj.","",""),
		new Array("8","rule","尺；規則；統治","n. / v.","",""),
		new Array("8","respond","回應；反應","v.","",""),
		new Array("8","response","回應；反應","n.","",""),
		new Array("8","respondent","有反應的；被告","adj. / n.","",""),
		new Array("8","appropriate","適當的","adj."," = proper",""),
		new Array("8","inappropriate","不適當的；不合宜的","adj."," = improper",""),
		new Array("8","informal","非正式的","adj.","",""),
		new Array("8","formal","正式的","adj.","",""),
		new Array("8","manner","方式；禮貌","n.","",""),
		new Array("8","involve","牽涉；涉及；參與","v.","",""),
		new Array("8","board","板子","n.","",""),
		new Array("8","familiar","熟悉的","adj.","",""),
		new Array("8","familiarize","使熟悉","v.","familiarize A with B 使A熟悉B",""),
		new Array("8","unfamiliar","不熟悉的","adj.","",""),
		new Array("8","compose","寫作","v.","",""),
		new Array("8","style","風格","n.","",""),
		new Array("8","aim","目標；針對…；設定目標","n. / v.","",""),
		new Array("8","etiquette","禮儀","n.","",""),
		new Array("8","workforce","勞動人口","n.","",""),
		new Array("8","correspondence","書信；通信","n.","",""),
		new Array("8","honest","誠實的","adj.","",""),
		new Array("8","muggy","悶熱的","adj.","","")
	),
	//5
	new Array(
		new Array("1","decorate","裝飾","v.","",""),
		new Array("1","wedding","婚禮","n.","",""),
		new Array("1","vary","變化；改變","v.","",""),
		new Array("1","various","各式各樣的","adj.","",""),
		new Array("1","variety","有變化；多樣性","n.","",""),
		new Array("1","reception","招待會；款待；領受","n.","",""),
		new Array("1","receive","接待；收到","v.","",""),
		new Array("1","ceremony","典禮；儀式","n.","",""),
		new Array("1","tradition","傳統","n.","",""),
		new Array("1","traditional","傳統的","adj.","",""),
		new Array("1","bride","新娘","n.","",""),
		new Array("1","bridal","新娘的","adj.","",""),
		new Array("1","bridesmaid","女儐相；伴娘","n.","",""),
		new Array("1","likely","可能的；大概地","adj. / adv.","",""),
		new Array("1","alike","同樣地","adv.","",""),
		new Array("1","plastic","塑膠製成的；塑膠","adj. / n.","",""),
		new Array("1","groom","新郎","n.","",""),
		new Array("1","Greece","希臘","n.","",""),
		new Array("1","oven","烤箱","n.","",""),
		new Array("1","ring","戒指；一通電話","n.","",""),
		new Array("1","delicate","美味的；易碎的；精巧的","adj.","",""),
		new Array("1","delicacy","精緻；優美；嬌嫩；佳餚","n.","",""),
		new Array("1","elaborate","精巧的；精製的","adj.","",""),
		new Array("1","frosting","糖霜","n.","",""),
		new Array("1","frost","霜；結霜","n. / v.","",""),
		new Array("1","flavor","味道","n.","",""),
		new Array("1","bakery","麵包店；糕餅店","n.","",""),
		new Array("1","bake","烤","v.","",""),
		new Array("1","baker","麵包師傅","n.","",""),
		new Array("1","private","私人的；私立的","adj.","",""),
		new Array("1","privacy","隱私(權)","n.","",""),
		new Array("1","freeze","冷凍；結冰；凍結(資產)","v.","pt.為froze pp.為frozen",""),
		new Array("1","annual","每年的；一年一次的","adj."," = yearly",""),
		new Array("1","anniversary","週年紀念日","n.","",""),
		new Array("1","pillow","枕頭","n.","",""),
		new Array("1","Hollywood","好萊塢","n.","",""),
		new Array("1","pastel","(色彩)柔和的；淡的","adj.","",""),
		new Array("1","icing","糖衣；糖霜","n.","",""),
		new Array("1","batter","重擊；糊狀物","v. / adj.","",""),
		new Array("1","underneath","在...下面","prep.","",""),
		new Array("1","best man","男儐相；伴郎","n.","",""),
		new Array("1","be covered with","鼠(單數)","片語","",""),
		new Array("1","be supposed to","洞；孔","片語","",""),
		new Array("1","pick up","農舍","片語","",""),
		new Array("2","instruct","指導；教導；命令","v.","",""),
		new Array("2","instruction","說明書；使用指南","n.","",""),
		new Array("2","software","軟體","n.","",""),
		new Array("2","imagine","想像","v.","",""),
		new Array("2","imaginative","富有想像力的","adj.","",""),
		new Array("2","imagination","想像力","n.","",""),
		new Array("2","digital","數字的；數位的","adj.","",""),
		new Array("2","ruin","毀滅；破壞","n. / v."," = destroy",""),
		new Array("2","drill","鑽孔機；練習","n.","",""),
		new Array("2","ignore","忽略；漠視","v."," = neglect = overlook",""),
		new Array("2","ignorance","無知；愚昧","n.","",""),
		new Array("2","direction","方向；指示；用法說明","n.","",""),
		new Array("2","safety","安全","n.","",""),
		new Array("2","metal","金屬","n.","",""),
		new Array("2","furthermore","而且；再者","adv."," = moreover    = in addition",""),
		new Array("2","operate","操作","v.","",""),
		new Array("2","operation","動作；手術","n."," = surgery (手術)",""),
		new Array("2","warn","警告","v.","",""),
		new Array("2","warning","警告","n.","",""),
		new Array("2","extra","額外的","adj.","",""),
		new Array("2","usage","用法；使用","n.","",""),
		new Array("2","recommend","推薦","v.","",""),
		new Array("2","recommendation","推薦；推薦信","n.","",""),
		new Array("2","dosage","劑量","n.","",""),
		new Array("2","drowsy","想睡的","adj."," = sleepy",""),
		new Array("2","drowsiness","睏倦","n.","",""),
		new Array("2","cautious","小心的","adj.","",""),
		new Array("2","caution","小心","n.","",""),
		new Array("2","machine","機器","n.","",""),
		new Array("2","pregnant","懷孕的","adj.","",""),
		new Array("2","pregnancy","懷孕","n.","",""),
		new Array("2","drug","藥物","n.","",""),
		new Array("2","damage","傷害","n. / v.","",""),
		new Array("2","swing","鞦韆；擺動；轉動","n. / v.","",""),
		new Array("2","insert","插入","n. / v.","",""),
		new Array("2","grounds","粉末","n.","",""),
		new Array("2","tank","槽；罐","n.","",""),
		new Array("2","desire","慾望；想要","n. / v.","",""),
		new Array("2","switch","開關；打開(或關閉)電器","n. / v.","",""),
		new Array("2","onto","到…之上","prep.","",""),
		new Array("2","disc","(電腦)記憶體；磁碟","n.","",""),
		new Array("2","capsule","膠囊","n.","",""),
		new Array("2","bedtime","就寢時間","n.","",""),
		new Array("2","coffeemaker","咖啡機","n.","",""),
		new Array("2","filter","過濾器","n.","",""),
		new Array("2","approximately","大約","adv.","",""),
		new Array("2","save A from B","拯救A免於B","片語","",""),
		new Array("2","end up + V-ing","結果是…","片語","",""),
		new Array("2","look up","查閱","片語","",""),
		new Array("2","out of the reach of…","在…所及的範圍之外","片語","",""),
		new Array("3","obstacle","障礙物","n.","",""),
		new Array("3","fortunately","幸運地","adv.","",""),
		new Array("3","separate","分開；分居；個別的","v. / adj.","",""),
		new Array("3","divorce","離婚","n. / v.","",""),
		new Array("3","resentful","忿忿不平的","adj.","",""),
		new Array("3","resent","憤慨","v.","",""),
		new Array("3","upset","心煩意亂的；生氣的","adj.","",""),
		new Array("3","odd","奇怪的；奇數的","adj.","",""),
		new Array("3","envy","羨慕；妒忌","n. / v.","",""),
		new Array("3","envious","羨慕的；妒忌的","adj.","",""),
		new Array("3","downstairs","在樓下","adv.","",""),
		new Array("3","neat","整齊的；乾淨的","adj.","",""),
		new Array("3","iron","熨斗；鐵；燙(衣服)","n. / v.","",""),
		new Array("3","invite","邀請","v.","",""),
		new Array("3","invitation","邀請","n.","",""),
		new Array("3","luxury","奢侈(品)","n.","",""),
		new Array("3","luxurious","奢侈的","adj.","",""),
		new Array("3","precious","珍貴的；貴重的","adj.","",""),
		new Array("3","wealth","財富","n."," = fortune",""),
		new Array("3","wealthy","有錢的；富有的","adj.","",""),
		new Array("3","grownup","長大成人的；成人","adj. / n.","",""),
		new Array("3","widow","寡婦","n.","",""),
		new Array("3","widower","鰥夫","n.","",""),
		new Array("3","widowed","喪夫的；喪妻的","adj.","",""),
		new Array("3","shame","羞愧；可惜之事","n.","",""),
		new Array("3","ashamed","覺得慚愧的","adj.","",""),
		new Array("3","shameful","可恥的","adj.","",""),
		new Array("3","immigrant","外來移民","n.","",""),
		new Array("3","immigrate","由外國移民近來","v.","",""),
		new Array("3","made-up","杜撰的；想像的；化妝品","adj. / n.","",""),
		new Array("3","image","形象；意象","n.","",""),
		new Array("3","convention","習慣；常規；會議","n.","",""),
		new Array("3","conventional","傳統的；普通的","adj.","",""),
		new Array("3","unique","獨特的","adj.","",""),
		new Array("3","blend","混合；混合物","v. / n.","",""),
		new Array("3","blender","攪拌機","n.","",""),
		new Array("3","overcome","克服；戰勝","v."," = conquer",""),
		new Array("3","trailer","拖車","n.","",""),
		new Array("3","row house","連動的房子","n.","",""),
		new Array("3","overalls","工作褲","n.","",""),
		new Array("3","be different from","與…不同","片語","",""),
		new Array("3","most of all","尤其；特別；最…","片語","",""),
		new Array("3","make up the rules","制定規則","片語","",""),
		new Array("3","be close to","親近","片語","",""),
		new Array("3","way of living","生活方式","片語"," = lifestyle",""),
		new Array("4","toothbrush","牙刷","n.","",""),
		new Array("4","zipper","拉鍊","n.","",""),
		new Array("4","ballpoint","原子筆","n.","",""),
		new Array("4","bulb","燈泡","n.","",""),
		new Array("4","sense","感覺","n.","",""),
		new Array("4","exist","存在","v.","",""),
		new Array("4","existence","存在","n.","",""),
		new Array("4","fulfill","完成；實行","v."," = carry out",""),
		new Array("4","forest","森林","n.","",""),
		new Array("4","fur","毛皮","n.","",""),
		new Array("4","microscope","顯微鏡","n.","",""),
		new Array("4","hook","鉤子","n.","",""),
		new Array("4","loop","圈狀物","n.","",""),
		new Array("4","fastener","黏繫物","n.","",""),
		new Array("4","fasten","固定","v.","",""),
		new Array("4","spacesuit","太空衣","n.","",""),
		new Array("4","wound","傷口；弄傷","n. / v.","",""),
		new Array("4","wounded","受傷的","adj.","",""),
		new Array("4","amazing","令人驚奇的","adj."," = astonishing",""),
		new Array("4","infect","感染","v.","",""),
		new Array("4","infectious","有感染力的","adj.","",""),
		new Array("4","infection","感染；傳染病","n.","",""),
		new Array("4","bacteria","細菌","n.","單數為bacterium",""),
		new Array("4","cotton","棉","n.","",""),
		new Array("4","bandage","繃帶","n.","",""),
		new Array("4","sterile","無菌的","adj.","",""),
		new Array("4","similar","相似的","adj.","",""),
		new Array("4","strip","狹長一片","n.","",""),
		new Array("4","Velcro","魔鬼貼","n.","",""),
		new Array("4","Swiss","瑞士的","adj. ","",""),
		new Array("4","burr","針毬","n.","",""),
		new Array("4","Band-Aid","OK繃；急救繃帶","n.","",""),
		new Array("4","adhesive","有黏性的；黏著劑","adj. / n.","",""),
		new Array("4","take a walk","散步","片語"," = go for a walk",""),
		new Array("4","before long","很快地","片語","",""),
		new Array("4","by oneself","獨自","片語","",""),
		new Array("5","replace","取代","v."," = in place of",""),
		new Array("5","admire","讚揚；稱讚","v.","",""),
		new Array("5","necklace","項鍊","n.","",""),
		new Array("5","charming","迷人的","adj.","",""),
		new Array("5","charm","魅力；魔力","n.","",""),
		new Array("5","clerk","職員；辦事員","n.","",""),
		new Array("5","education","教育","n.","",""),
		new Array("5","continue","繼續","v.","",""),
		new Array("5","continual","持續的","adj.","",""),
		new Array("5","deserve","應得；值得","v.","",""),
		new Array("5","deserving","值得的","adj.","",""),
		new Array("5","regret","悔恨；遺憾","v. / n.","",""),
		new Array("5","regretful","懊悔的；遺憾的","adj.","",""),
		new Array("5","despair","絕望","n.","",""),
		new Array("5","despairing","絕望的","adj.","",""),
		new Array("5","disappoint","令…失望","v.","",""),
		new Array("5","disappointed","覺得失望的","adj.","",""),
		new Array("5","disappointing","令人失望的","adj.","",""),
		new Array("5","disappointment","失望","n.","",""),
		new Array("5","occasion","時機；場合","n.","",""),
		new Array("5","occasional","偶爾的","adj.","",""),
		new Array("5","schoolmate","同窗；同校同學","n.","",""),
		new Array("5","tremble","發抖；震顫","n. / v.","",""),
		new Array("5","diamond","鑽石","n.","",""),
		new Array("5","elegant","優雅的","adj.","",""),
		new Array("5","enthusiasm","熱忱；熱心","n.","",""),
		new Array("5","enthusiastic","熱心的","adj.","",""),
		new Array("5","nearly","幾乎；大概","adv.","",""),
		new Array("5","mirror","鏡子","n.","",""),
		new Array("5","suddenly","突然地","adv."," = all at once",""),
		new Array("5","utter","說出","v.","",""),
		new Array("5","utterance","發聲；發言","n.","",""),
		new Array("5","toward(s)","向…；朝…","prep.","",""),
		new Array("5","dismay","驚愕","n.","",""),
		new Array("5","debt","債","n.","",""),
		new Array("5","interest","利息；興趣；使…感興趣","n. / v.","",""),
		new Array("5","satisfy","使…滿意","v.","",""),
		new Array("5","satisfied","覺得滿意的","adj. ","",""),
		new Array("5","satisfying","令人滿意的","adj. ","",""),
		new Array("5","satisfaction","滿意(足)","n.","",""),
		new Array("5","naive","純真的；天真的","adj."," = innocent",""),
		new Array("5","FALSE","假的；錯誤的","adj.","",""),
		new Array("5","in a cloud of","在一種…氣氛之中","片語","",""),
		new Array("5","no longer","不再","片語"," = not...anymore",""),
		new Array("6","crossroads","十字路口","n.","單、複數同形",""),
		new Array("6","decide","決定","v.","",""),
		new Array("6","decision","決定","n.","",""),
		new Array("6","decisive","果斷的；決定性的","adj.","",""),
		new Array("6","career","事業；職業；生涯","n.","",""),
		new Array("6","alternative","另一個選擇；變通辦法","n.","",""),
		new Array("6","advantage","好處；優點","n.","",""),
		new Array("6","advantageous","有利的；有益的","adj.","",""),
		new Array("6","disadvantage","缺點","n.","",""),
		new Array("6","ultimately","最終(後)地","adv."," = finally",""),
		new Array("6","following","接著的","adj.","",""),
		new Array("6","bend","彎曲","v.","",""),
		new Array("6","fair","美好的；公平的","adj. ","",""),
		new Array("6","unfair","不公平的","adj. ","",""),
		new Array("6","unfairly","不公平地","adv.","",""),
		new Array("6","claim","宣稱","v. / n.","",""),
		new Array("6","grass","草地","n.","",""),
		new Array("6","grassy","長滿草的","adj.","",""),
		new Array("6","wear","穿；磨損；耐磨性","v. / n.","",""),
		new Array("6","equal","相等的","adj.","",""),
		new Array("6","equality","平等；同等","n.","",""),
		new Array("6","tread","踩踏；腳步聲","v. / n.","",""),
		new Array("6","doubt","懷疑","v. / n.","",""),
		new Array("6","doubtful","懷疑的","adj.","",""),
		new Array("6","sigh","嘆氣","n. / v.","",""),
		new Array("6","hence","因此","adv.","",""),
		new Array("6","diverge","分岔；分歧","v.","",""),
		new Array("6","divergence","分岔；分歧","n.","",""),
		new Array("6","at times","有時候；偶爾","片語"," = once in a while",""),
		new Array("6","a turning point","轉折點","片語","",""),
		new Array("6","lead to","導致","片語"," = result in = cause",""),
		new Array("6","as far as one could","(到)最遠處","片語","",""),
		new Array("6","as for","至於","片語","",""),
		new Array("6","lead on to","通往","片語","",""),
		new Array("6","ages and ages","多年","片語","",""),
		new Array("6","make the difference","有(重大)影響；造成不同","片語","",""),
		new Array("7","author","作者","n.","",""),
		new Array("7","whereas","反之；而...","conj.","",""),
		new Array("7","describe","敘述；描述","v.","",""),
		new Array("7","description","敘述；描述","n.","",""),
		new Array("7","act","舉止；表現","v.","",""),
		new Array("7","active","主動的；活動的；積極的","adj.","",""),
		new Array("7","action","行動；行為","n.","",""),
		new Array("7","merely","僅僅；只是","adv.","",""),
		new Array("7","stereotype","刻版印象；賦予刻版印象","n. / v.","",""),
		new Array("7","passive","消極的；被動的","adj.","",""),
		new Array("7","nurture","教養；養育","n. / v.","",""),
		new Array("7","nurturing","善於養育照顧的","adj.","",""),
		new Array("7","physical","身體的；外在的","adj.","",""),
		new Array("7","strength","力量；強度；濃度","n.","",""),
		new Array("7","strengthen","加強；增強","v.","",""),
		new Array("7","firefighter","消防隊員","n. ","",""),
		new Array("7","mechanic","機械工；技工","n. ","",""),
		new Array("7","mechanical","機械的","adj.","",""),
		new Array("7","require","要求","v.","",""),
		new Array("7","requirement","需要；必需品","n.","",""),
		new Array("7","secretary","秘書","n. ","",""),
		new Array("7","patient","有耐心的；病人","adj. / n.","",""),
		new Array("7","patience","耐心","n.","",""),
		new Array("7","rational","理性的","adj.","",""),
		new Array("7","subject","科目；學科；主題","n.","",""),
		new Array("7","logical","邏輯上的","adj.","",""),
		new Array("7","thinking","思想","n.","",""),
		new Array("7","intuition","直覺","n.","",""),
		new Array("7","believe","相信","v.","",""),
		new Array("7","belief","信念；信仰","n.","",""),
		new Array("7","critic","批評家；評論家","n.","",""),
		new Array("7","criticize","批評；批判","v.","",""),
		new Array("7","critical","批評的","adj.","",""),
		new Array("7","rough","粗暴的；粗糙的；表面不平的","adj.","",""),
		new Array("7","employ","雇用","v.","",""),
		new Array("7","employee","受雇者；雇員","n.","",""),
		new Array("7","employer","雇主","n.","",""),
		new Array("7","employment","就業；工作","n.","",""),
		new Array("7","promote","升遷；晉升","v.","",""),
		new Array("7","promotion","升遷；晉級","n.","",""),
		new Array("7","judge","審判；法官","v. / n.","",""),
		new Array("7","judgment","判斷；審判","n.","",""),
		new Array("7","treat","對待；治療","v.","",""),
		new Array("7","treatment","對待；治療","n.","",""),
		new Array("7","unkind","不友善的；不仁慈的","adj.","",""),
		new Array("7","unkindly","不友善地；刻薄地","adv.","",""),
		new Array("7","lump","把...歸併一起；把...混為一談","v.","",""),
		new Array("7","category","種類","n.","",""),
		new Array("7","be based on","基於...；根據...","片語","",""),
		new Array("7","on the basis of ","基於...","片語","",""),
		new Array("7","on the other hand","在另外一方面...","片語","",""),
		new Array("7","to some degree","某個程度上","片語","",""),
		new Array("7","make fun of","取笑；捉弄","片語","",""),
		new Array("7","look down upon","輕視","片語"," = despise",""),
		new Array("7","turn down","拒絕","片語"," = refuse = reject",""),
		new Array("8","ancient","古代的","adj.","",""),
		new Array("8","scale","規模；秤","n.","",""),
		new Array("8","ability","能力","n.","",""),
		new Array("8","able","能夠的","adj.","",""),
		new Array("8","warrior","戰士；勇士","n.","",""),
		new Array("8","practice","慣例；常規；練習","n.","",""),
		new Array("8","standard","標準","n.","",""),
		new Array("8","parade","遊行","n. / v.","",""),
		new Array("8","sacrifice","犧牲；祭品；獻祭","n. / v.","",""),
		new Array("8","gold","黃金；金子","n.","",""),
		new Array("8","golden","金製的；金色的","adj.","",""),
		new Array("8","silver","銀；銀製(色)的","n. / adj.","",""),
		new Array("8","medal","獎牌；勳章","n.","",""),
		new Array("8","crown","桂冠；皇冠","n.","",""),
		new Array("8","participate","參加","v.","",""),
		new Array("8","participant","參加者","n.","",""),
		new Array("8","participation","參與","n.","",""),
		new Array("8","citizen","公民；國民","n.","",""),
		new Array("8","handicapped","殘障的","adj.","",""),
		new Array("8","concept","觀念；概念","n.","",""),
		new Array("8","means","手段；途徑；方法","n.","",""),
		new Array("8","victory","勝利","n.","",""),
		new Array("8","propose","提出建議","v.","",""),
		new Array("8","establish","建立；創辦","v.","",""),
		new Array("8","establishment","設立","n.","",""),
		new Array("8","flag","旗子(幟)","n.","",""),
		new Array("8","cooperate","合作；團結","v.","",""),
		new Array("8","cooperation","合作","n.","",""),
		new Array("8","goodwill","友好；善意","n.","",""),
		new Array("8","alive","活的；仍存在的","adj.","",""),
		new Array("8","torch","火炬；火把","n.","",""),
		new Array("8","host","主人","n.","",""),
		new Array("8","ritual","儀式","n.","",""),
		new Array("8","potential","潛力；潛在的","n. / adj.","",""),
		new Array("8","achieve","到達；完成","v.","",""),
		new Array("8","achievement","成就；達成","n.","",""),
		new Array("8","celebrate","慶祝","v.","",""),
		new Array("8","Olympics","奧林匹亞運動會","n.","",""),
		new Array("8","boxing","拳擊","n.","",""),
		new Array("8","showy","華麗的","adj.","",""),
		new Array("8","nude","裸體","n.","",""),
		new Array("8","cycling","騎自行車運動","n.","",""),
		new Array("8","sailing","帆船比賽；行船","n.","",""),
		new Array("8","shooting","涉及","n.","",""),
		new Array("8","prowess","英勇；好本事","n.","",""),
		new Array("8","focus on","把焦點集中於...","片語","",""),
		new Array("8","show off","炫耀；賣弄","片語","",""),
		new Array("8","take part in","參加","片語","",""),
		new Array("8","as well","另外...，也是...","片語","",""),
		new Array("8","not only...but (also)","不但...，而且...","片語","",""),
		new Array("8","consist of","組成","片語"," = be made up of = be composed of",""),
		new Array("8","stand for","代表","片語"," = represent",""),
		new Array("8","date back to","追溯至...","片語","",""),
		new Array("8","most important of all","最重要的是...","片語","","")
	),
	//6
	new Array(
		new Array("1","portion","部分","n.","",""),
		new Array("1","landscape","景色；風景","n.","",""),
		new Array("1","snack","小吃；點心","n.","",""),
		new Array("1","locate","座落於...；找出人或東西的位置","v.","",""),
		new Array("1","location","位置","n.","",""),
		new Array("1","culture","文化","n.","",""),
		new Array("1","cultural","文化的","adj.","",""),
		new Array("1","treasure","瑰寶；寶藏；珍惜","n. / v.","",""),
		new Array("1","brick","磚塊；用磚砌成","n.","",""),
		new Array("1","offer","提供；提議","n. / v.","",""),
		new Array("1","suggest","意味；建議","v.","",""),
		new Array("1","suggestion","建議","n.","",""),
		new Array("1","colorful","多采多姿的；富色彩的","adj.","",""),
		new Array("1","community","社區","n.","",""),
		new Array("1","old-fashioned","老式的","adj.","",""),
		new Array("1","populate","居住於...","v.","",""),
		new Array("1","population","人口","n.","",""),
		new Array("1","decade","十年","n.","",""),
		new Array("1","eventually","最後地","adv."," = finally",""),
		new Array("1","mine","礦場；採礦","n. / v.","",""),
		new Array("1","miner","礦工","n.","",""),
		new Array("1","especially","特別地；尤其","adv."," = particularly",""),
		new Array("1","paint","繪畫；顏料；油漆","v. / n.","",""),
		new Array("1","painter","畫家；油漆匠","n.","",""),
		new Array("1","exhibit","展覽","v.","",""),
		new Array("1","exhibition","展覽會","n.","",""),
		new Array("1","film","影片；膠捲；拍攝電影","n. / v.","",""),
		new Array("1","filmmaker","製片人","n. ","",""),
		new Array("1","tour","旅遊；觀光","n. / v.","",""),
		new Array("1","tourist","遊客","n.","",""),
		new Array("1","destination","目的地","n.","",""),
		new Array("1","destined","注定的","adj.","",""),
		new Array("1","destiny","命運","n."," = fate",""),
		new Array("1","mountainside","山坡","n.","",""),
		new Array("1","the Pacific Ocean","太平洋","n.","",""),
		new Array("1","start as","以...開始","片語","",""),
		new Array("2","disease","疾病","n.","",""),
		new Array("2","fries","炸薯條","n.","",""),
		new Array("2","fry","油煎；油炸","v.","",""),
		new Array("2","fried","油煎的；油炸的","adj.","",""),
		new Array("2","potato","馬鈴薯","n.","",""),
		new Array("2","crop","農作物；收成","n.","",""),
		new Array("2","wheat","小麥","n.","",""),
		new Array("2","corn","玉米；玉蜀黍","n.","",""),
		new Array("2","Europe","歐洲","n.","",""),
		new Array("2","European","歐洲的；歐洲人","adj. / n.","",""),
		new Array("2","seek","尋找；尋求","v.","",""),
		new Array("2","weird","怪誕的；怪異的","adj.","",""),
		new Array("2","underground","地下的","adj.","",""),
		new Array("2","soil","土壤","n.","",""),
		new Array("2","climate","氣候","n.","",""),
		new Array("2","hunger","飢餓；肚子餓；渴望","n.","",""),
		new Array("2","hungry","飢餓的","adj.","",""),
		new Array("2","great-grandfather","(外)曾祖父","n.","",""),
		new Array("2","national","國家的","adj.","",""),
		new Array("2","international","國際性的","adj.","",""),
		new Array("2","nationality","國籍","n.","",""),
		new Array("2","dish","盤子；菜餚","n.","",""),
		new Array("2","mash","搗碎","v.","",""),
		new Array("2","globe","地球；球狀物","n.","",""),
		new Array("2","global","全球的","adj.","",""),
		new Array("2","vinegar","醋","n.","",""),
		new Array("2","pepper","胡椒","n.","",""),
		new Array("2","ketchup","番茄醬","n.","",""),
		new Array("2","Peru","祕魯(國家名稱)","n.","",""),
		new Array("2","Ireland","愛爾蘭","n.","",""),
		new Array("2","in the past","以前","片語","",""),
		new Array("2","die of","因...而死","片語","",""),
		new Array("2","rather than","而不是","片語","",""),
		new Array("2","prefer to V rather than V","寧願...而不願意...","片語","",""),
		new Array("2","prefer V-ing to V-ing","喜歡A勝過於喜歡B","片語","",""),
		new Array("3","tire","輪胎","n.","",""),
		new Array("3","billion","十億","n.","",""),
		new Array("3","truck","貨車；卡車","n.","",""),
		new Array("3","remain","維持；保持","v.","",""),
		new Array("3","material","材料；資料；物質上的","n. / adj.","",""),
		new Array("3","prevent","避免","v.","",""),
		new Array("3","pollute","污染","v.","",""),
		new Array("3","pollution","污染","n.","",""),
		new Array("3","pollutant","污染物","n.","",""),
		new Array("3","dump","垃圾場；傾倒","n. / v.","",""),
		new Array("3","landfill","垃圾掩埋場","n.","",""),
		new Array("3","environment","環境","n.","",""),
		new Array("3","environmental","環境的","adj.","",""),
		new Array("3","environmentalist","環保主義者","n.","",""),
		new Array("3","attract","吸引","v.","",""),
		new Array("3","attractive","吸引人的","adj.","",""),
		new Array("3","attraction","吸引力","n.","",""),
		new Array("3","mosquito","蚊子","n.","",""),
		new Array("3","rat","老鼠","n.","",""),
		new Array("3","spread","散佈；傳播；攤開","n. / v.","",""),
		new Array("3","release","排放；釋放","n. / v.","",""),
		new Array("3","nearby","附近的；在附近","adj. / adv.","",""),
		new Array("3","chemical","化學的；化學製品","adj. / n.","",""),
		new Array("3","represent","代表；象徵","v."," = stand for",""),
		new Array("3","waste","廢棄物；浪費","n. / v.","",""),
		new Array("3","resource","資源","n.","",""),
		new Array("3","recycle","回收","v.","",""),
		new Array("3","recycled","回收的","adj.","",""),
		new Array("3","recycling","資源回收","n.","",""),
		new Array("3","solve","解決；解答","v.","",""),
		new Array("3","solution","解決；解答","n.","",""),
		new Array("3","energy","能源；精力","n.","",""),
		new Array("3","energetic","精力旺盛的","adj.","",""),
		new Array("3","plant","廠房；植物","n.","",""),
		new Array("3","steam","水蒸氣","n.","",""),
		new Array("3","proper","適當的；合適的","adj."," = appropriate",""),
		new Array("3","chimney","煙囪","n.","",""),
		new Array("3","total","總括的；完全的；合計；總數","adj. / n.","",""),
		new Array("3","supply","供應品；補充","n. / v.","",""),
		new Array("3","doormat","門墊","n.","",""),
		new Array("3","solid","牢固的；堅實的","adj.","",""),
		new Array("3","bump","重擊；碰撞","n. / v.","",""),
		new Array("3","form","外形；表格；成立；組織","n. / v.","",""),
		new Array("3","surface","表面；表層","n. / v.","",""),
		new Array("3","blanket","毛毯；全面的；總括的；覆蓋","n. / adj. / v.","",""),
		new Array("3","smooth","平整的；平滑的","adj.","",""),
		new Array("3","worn-out","破損的；用壞的","adj.","",""),
		new Array("3","generate","產生","v.","",""),
		new Array("3","sole","鞋底","n.","",""),
		new Array("3","mountains of ","大量的","片語"," = a large amount of",""),
		new Array("3","a number of","很多的","片語","",""),
		new Array("3","put out","撲滅","片語","",""),
		new Array("3","at large expense","花費巨大的費用","片語","",""),
		new Array("3","As long as S + V, S + V…","只要…","片語","",""),
		new Array("4","athletic","運動的；強健的","adj.","",""),
		new Array("4","effective","有效的","adj.","",""),
		new Array("4","consumer","顧客；消費者","n.","",""),
		new Array("4","consume","消費；消耗","v.","",""),
		new Array("4","consumption","消費；消耗量","n.","",""),
		new Array("4","information","資料","n.","",""),
		new Array("4","specific","明確的；特定的","adj.","",""),
		new Array("4","ingredient","成分；材料","n.","",""),
		new Array("4","appeal","吸引；吸引力","v. / n.","",""),
		new Array("4","immediate","立即的","adj.","",""),
		new Array("4","behavior","行為","n.","",""),
		new Array("4","affect","影響","v.","",""),
		new Array("4","language","語言","n.","",""),
		new Array("4","catchy","簡單好記的；引起注意的","adj.","",""),
		new Array("4","slogan","標語；口號","n.","",""),
		new Array("4","advertising","廣告的；廣告業","adj. / n.","",""),
		new Array("4","campaign","(為達某一目的所做的)活動","n.","",""),
		new Array("4","equivalent","同等(人)物；同等的","n. / adj.","",""),
		new Array("4","principle","原理；原則","n.","",""),
		new Array("4","attention","注意；注意力","n.","",""),
		new Array("4","attentive","留心的；注意的","adj.","",""),
		new Array("4","hire","僱用","v."," =employ",""),
		new Array("4","celebrity","名人；名聲","n.","",""),
		new Array("4","celebrated","有名的","adj."," = famous",""),
		new Array("4","arouse","激起；引起；喚起","v.","",""),
		new Array("4","commercial","電視廣告；商業的","n. / adj.","",""),
		new Array("4","commerce","商業；商務","n.","",""),
		new Array("4","frequent","時常的；頻繁的","adj.","",""),
		new Array("4","frequently","常常；頻繁地","adv.","",""),
		new Array("4","frequency","頻繁；頻率","n.","",""),
		new Array("4","prestige","名望；聲望","n.","",""),
		new Array("4","prestigious","有名望的；有聲望的","adj.","",""),
		new Array("4","issue","問題；發行","n. / v.","",""),
		new Array("4","limit","界線；限制","n. / v.","",""),
		new Array("4","limited","有限制的","adj.","",""),
		new Array("4","certain","某些的；確信的","adj.","",""),
		new Array("4","certainty","確信；確實","n.","",""),
		new Array("4","effectively","有效地","adv.","",""),
		new Array("4","retail","零售","n. / v.","",""),
		new Array("4","retailer","零售商","n.","",""),
		new Array("4","budget","預算","n.","",""),
		new Array("4","day-to-day","每日的；日常的","adj.","",""),
		new Array("4","jingle","廣告歌","n. ","",""),
		new Array("4","for instance","例如；舉例來說","片語"," = for example",""),
		new Array("4","in turn","依次","片語","",""),
		new Array("4","play a role (in)","(在…)扮演角色","片語","",""),
		new Array("4","may very well","有可能","片語","",""),
		new Array("5","honest","誠實的","adj.","",""),
		new Array("5","challenge","挑戰","n. / v.","",""),
		new Array("5","brave","勇敢的","adj.","",""),
		new Array("5","defeat","擊敗；戰敗","n. / v.","",""),
		new Array("5","humble","謙遜的；謙卑的","adj.","",""),
		new Array("5","foundation","根據；基礎；基金會","n.","",""),
		new Array("5","found","建立；創立","v.","",""),
		new Array("5","founder","創立者","n.","",""),
		new Array("5","knowledge","知識","n.","",""),
		new Array("5","path","路徑","n. ","",""),
		new Array("5","stress","壓力；強調","n. / v.","",""),
		new Array("5","stressful","有壓力的","adj.","",""),
		new Array("5","spur","驅策；激勵；鞭策","n. / v.","",""),
		new Array("5","compassion","同情；憐憫","n. "," = sympathy",""),
		new Array("5","compassionate","有同情心的","adj."," = sympathetic",""),
		new Array("5","failure","失敗；失敗的人或事","n. ","",""),
		new Array("5","goal","目標","n. ","",""),
		new Array("5","master","主人；駕馭；精通","n. / v.","",""),
		new Array("5","weep","哭泣；落淚","v.","",""),
		new Array("5","humor","幽默","n. ","",""),
		new Array("5","humorous","幽默的","adj.","",""),
		new Array("5","humility","謙恭；謙卑；謙遜","n. ","",""),
		new Array("5","simplicity","單純；樸素","n. ","",""),
		new Array("5","simplify","簡化","v.","",""),
		new Array("5","wisdom","智慧","n. ","",""),
		new Array("5","meek","溫順的","adj.","",""),
		new Array("5","dare","膽敢","v.","",""),
		new Array("5","whisper","低聲；輕聲說","n. / v.","",""),
		new Array("5","unbending","執著的；固執的","adj.","",""),
		new Array("5","sense of humor","幽默感","片語","",""),
		new Array("6","manufacturer","製造商","n.","",""),
		new Array("6","involve","牽涉；包含；參與…","v.","",""),
		new Array("6","technology","科技；技術","n.","",""),
		new Array("6","technological","科技的；技術的","adj.","",""),
		new Array("6","technician","技術人員","n.","",""),
		new Array("6","nanotechnology","奈米科技","n.","",""),
		new Array("6","single","單一的；單身的","adj.","",""),
		new Array("6","atom","原子","n.","",""),
		new Array("6","material","原料；材料；資料","n.","",""),
		new Array("6","level","程度","n.","",""),
		new Array("6","clothing","衣服(集合名詞)","n.","",""),
		new Array("6","expose","曝露","v.","",""),
		new Array("6","exposure","曝露；曝光率","n. ","",""),
		new Array("6","charge","充電；索價","n. / v.","",""),
		new Array("6","charger","充電器","n. ","",""),
		new Array("6","effort","努力；力氣；奮鬥","n.","",""),
		new Array("6","effortless","不費力的","adj.","",""),
		new Array("6","fit","適合；適應","v.","",""),
		new Array("6","fitting","合適的","adj.","",""),
		new Array("6","fitness","合適性","n.","",""),
		new Array("6","progress","進步","n. / v.","",""),
		new Array("6","progressive","漸進的；創新改革的","adj.","",""),
		new Array("6","storage","儲存空間；倉庫","n.","",""),
		new Array("6","biological","生物學的","adj.","",""),
		new Array("6","biology","生物","n.","",""),
		new Array("6","biologist","生物學家","n.","",""),
		new Array("6","cell","細胞；牢房","n.","",""),
		new Array("6","monitor","監視器；監視","n. / v.","",""),
		new Array("6","informative","具知識性的；使增廣見聞的","adj.","",""),
		new Array("6","inform","通知","v.","",""),
		new Array("6","harm","傷害；損害","n. / v.","",""),
		new Array("6","harmful","有害的","adj.","",""),
		new Array("6","expert","專家","n."," = specialist",""),
		new Array("6","concern","擔憂；令人擔心的事","n. / v.","",""),
		new Array("6","concerning","關於","prep."," = about",""),
		new Array("6","industry","工業；產業","n.","",""),
		new Array("6","industrial","工業的","adj.","",""),
		new Array("6","industrialize","工業化","v.","",""),
		new Array("6","responsible","負責的","adj.","",""),
		new Array("6","responsibility","責任","n.","",""),
		new Array("6","encounter","遭遇；偶遇","n. / v.","",""),
		new Array("6","stain","髒污；污漬；弄髒","n. / v.","",""),
		new Array("6","resistant","抗…的；抵抗的","adj.","",""),
		new Array("6","sunscreen","防曬油","n. ","",""),
		new Array("6","iPod","數位音樂播放器","n.","",""),
		new Array("6","dozens of","數十個…","片語","",""),
		new Array("6","in many ways","在許多方面","片語","",""),
		new Array("6","at this point","此時此刻","片語","",""),
		new Array("7","apologize","道歉","v.","",""),
		new Array("7","ignore","忽略；忽視","v."," = neglect = overlook",""),
		new Array("7","remote","遙遠的","adj.","",""),
		new Array("7","service","服務；保養檢修(車子)","n. / v.","",""),
		new Array("7","garage","車庫；修車廠","n.","",""),
		new Array("7","opportunity","機會","n."," = chance",""),
		new Array("7","readily","毫不遲疑地","adv.","",""),
		new Array("7","accept","接受","v.","",""),
		new Array("7","acceptable","可接受的","adj.","",""),
		new Array("7","acceptance","接納(受)","n.","",""),
		new Array("7","promise","承諾；答應","v.","",""),
		new Array("7","promising","前途無量的","adj.","",""),
		new Array("7","spare","多出(時間、金錢)可用；備用的","v. / adj.","",""),
		new Array("7","sparingly","少量使用","adv.","",""),
		new Array("7","immerse","浸入","v.","",""),
		new Array("7","immersed","沉溺的","adj.","",""),
		new Array("7","repair","修理","n. / v.","",""),
		new Array("7","rush","突如其來的感覺；一陣…","n.","",""),
		new Array("7","guilt","罪惡感","n.","",""),
		new Array("7","guilty","有罪的","adj.","",""),
		new Array("7","confess","認錯","v.","",""),
		new Array("7","confession","招認；自白","n.","",""),
		new Array("7","intent","專心的","adj.","",""),
		new Array("7","intently","專注地","adv.","",""),
		new Array("7","protest","抗議","n. / v.","",""),
		new Array("7","plead","懇求","v.","",""),
		new Array("7","silent","沉默的","adj.","",""),
		new Array("7","silence","沉默","n.","",""),
		new Array("7","per","每一…","prep.","",""),
		new Array("7","Spain","西班牙","n.","",""),
		new Array("7","feebly","軟弱地","adv.","",""),
		new Array("7","tardiness","延遲","n.","",""),
		new Array("7","contemplate","省思","v.","",""),
		new Array("7","relent","息怒；變溫和","v.","",""),
		new Array("7","distressing","令人苦惱的","adj.","",""),
		new Array("7","on the condition that ","在…條件之下就…","片語","",""),
		new Array("7","drop off","送達","片語","",""),
		new Array("7","lose track of","沒注意","片語","",""),
		new Array("7","show up","出現","片語"," = appear",""),
		new Array("7","bring up","養育","片語","",""),
		new Array("7","let...down","讓…失望","片語","",""),
		new Array("7","be about to","即將要…","片語","",""),
		new Array("8","creative","有創造力的","adj."," = original",""),
		new Array("8","creation","建立；創立","n.","",""),
		new Array("8","constant","持續的；一直的","adj.","",""),
		new Array("8","economy","經濟","n.","",""),
		new Array("8","economic","經濟上的","adj.","",""),
		new Array("8","forum","討論會","n.","",""),
		new Array("8","include","包括","v.","",""),
		new Array("8","development","發展","n.","",""),
		new Array("8","Switzerland","瑞士","n.","",""),
		new Array("8","conventional","傳統的","adj.","",""),
		new Array("8","object","物體；目標；反對","n. / v.","",""),
		new Array("8","castle","城堡","n.","",""),
		new Array("8","innovate","革新；創新","v.","",""),
		new Array("8","innovative","創新的；革新的","adj.","",""),
		new Array("8","innovator","改革者","n.","",""),
		new Array("8","innovation","革新；創新","n.","",""),
		new Array("8","topic","主題；題目","n.","",""),
		new Array("8","govern","統治","v.","",""),
		new Array("8","government","政府","n.","",""),
		new Array("8","social","社交的；群居的","adj.","",""),
		new Array("8","society","社會","n.","",""),
		new Array("8","workshop","研討會；工作坊","n.","",""),
		new Array("8","highlight","最突出的部份；強調；顯著","n. / v.","",""),
		new Array("8","strategy","策略","n.","",""),
		new Array("8","value","價值；重視","n. / v.","",""),
		new Array("8","valuable","有價值的","adj.","",""),
		new Array("8","undervalue","低估；輕視","v.","",""),
		new Array("8","numerous","許多的","adj.","",""),
		new Array("8","counterpart","相對應的人(或物)","n.","",""),
		new Array("8","skill","技巧","n.","",""),
		new Array("8","factor","因素；要素","n.","",""),
		new Array("8","firm","穩固的；公司；商號","adj. / n.","",""),
		new Array("8","concentrate","集中；全神貫注","v.","",""),
		new Array("8","originate","源自於…","v."," = derive",""),
		new Array("8","laboratory","實驗室","n.","",""),
		new Array("8","in-house","內部的","adj.","",""),
		new Array("8","tremendous","極大的；極好的","adj.","",""),
		new Array("8","approach","方法；靠近；接近","n. / v.","",""),
		new Array("8","textbook","課本；教科書","n.","",""),
		new Array("8","perspective","看法；觀點","n.","",""),
		new Array("8","tap","得到；輕拍","n. / v.","",""),
		new Array("8","Finland","芬蘭","n.","",""),
		new Array("8","be inclined to","有意願；有…傾向","片語","",""),
		new Array("8","come up with","想出","片語","",""),
		new Array("8","lag behind","落後","片語","",""),
		new Array("8","bring out","出版；引出；誘發","片語","",""),
		new Array("8","cutting edge","尖端；最重要位置","片語","","")
	)
/*
	//DEMO
	new Array(
	),
*/
);    